<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import DocumentWorkbench from "../../components/DocumentWorkbench.vue";
import {
  createAsset, createAssetWorkOrder, createMaintenancePlan, createServiceCase, createServiceVisit,
  generateMaintenanceWorkOrder, listAssetWorkOrders, listAssets, listEamAssignees, listMaintenancePlans,
  listServiceCases, listServiceContracts, listServiceVisits, transitionAssetWorkOrder, transitionServiceCase,
  updateAsset, updateAssetWorkOrder, updateServiceCase, updateServiceVisit,
} from "../../api/phase2";
import { useClientPagination } from "../../composables/useClientPagination";
import { useMasterOptions } from "../../composables/useMasterOptions";

type Row = Record<string, any>;
type DialogName = "asset" | "work-create" | "work-process" | "case-create" | "case-process" | "visit" | "plan" | "";

const activeTab = ref("assets"); const assets = ref<Row[]>([]); const workOrders = ref<Row[]>([]); const cases = ref<Row[]>([]); const plans = ref<Row[]>([]); const contracts = ref<Row[]>([]); const visits = ref<Row[]>([]); const assignees = ref<Array<{ value: string; label: string }>>([]); const loading = ref(false); const saving = ref(false); const actionLoading = ref<string | null>(null); const dialog = ref<DialogName>(""); const selectedRow = ref<Row | null>(null); const editingAssetId = ref(""); const transitionTarget = ref(""); const documentVisible = ref(false); const documentType = ref(""); const documentId = ref(""); const customerCaseFilter = ref("");
const { customers, loadOptions } = useMasterOptions();
const assetForm = reactive({ asset_code: "", asset_name: "", serial_no: "", location: "", next_maintenance_date: "", status: "active", retirement_reason: "" }); const planForm = reactive({ asset_id: "", name: "", interval_days: 30, next_due: "" }); const workForm = reactive({ asset_id: "", service_type: "repair", description: "", due_date: "", owner_id: "", maintenance_plan_id: "" }); const workProcessForm = reactive({ owner_id: "", resolution: "", actual_hours: 0, parts_cost: 0, labor_cost: 0 }); const caseForm = reactive({ customer_id: "", contract_id: "", title: "", priority: "normal", due_date: "", owner_id: "", sla_hours: 48 }); const caseProcessForm = reactive({ owner_id: "", resolution: "", customer_feedback: "", satisfaction_score: undefined as number | undefined }); const visitForm = reactive({ case_id: "", scheduled_at: "", technician_id: "", notes: "" }); const visitUpdateForm = reactive({ id: "", status: "scheduled", outcome: "", feedback_score: undefined as number | undefined });
const { pagedRows: assetRows, page: assetPage, pageSize: assetPageSize, total: assetTotal, updatePageSize: updateAssetPageSize } = useClientPagination(assets); const { pagedRows: workOrderRows, page: workOrderPage, pageSize: workOrderPageSize, total: workOrderTotal, updatePageSize: updateWorkOrderPageSize } = useClientPagination(workOrders); const { pagedRows: caseRows, page: casePage, pageSize: casePageSize, total: caseTotal, updatePageSize: updateCasePageSize } = useClientPagination(cases);

const serviceTypeLabels: Record<string, string> = { repair: "维修", maintenance: "保养", inspection: "点检" }; const priorityLabels: Record<string, string> = { low: "低", normal: "普通", high: "高", urgent: "紧急" }; const statusLabels: Record<string, string> = { open: "待分派", assigned: "已派工", in_progress: "处理中", resolved: "已解决", closed: "已关闭", cancelled: "已取消", reopened: "已重开", active: "在用", maintenance: "保养中", retired: "已报废", scheduled: "已安排", completed: "已完成" };
const workTransitions: Record<string, Array<{ to: string; label: string; type: string }>> = { open: [{ to: "assigned", label: "派工", type: "primary" }, { to: "cancelled", label: "取消", type: "danger" }], assigned: [{ to: "in_progress", label: "开始处理", type: "primary" }, { to: "cancelled", label: "取消", type: "danger" }], in_progress: [{ to: "resolved", label: "提交解决", type: "success" }, { to: "cancelled", label: "取消", type: "danger" }], resolved: [{ to: "closed", label: "验收关闭", type: "info" }, { to: "reopened", label: "重开", type: "warning" }], closed: [{ to: "reopened", label: "重开", type: "warning" }], reopened: [{ to: "in_progress", label: "继续处理", type: "primary" }, { to: "cancelled", label: "取消", type: "danger" }] }; const caseTransitions = workTransitions;
const filteredContracts = computed(() => contracts.value.filter((item) => !customerCaseFilter.value || String(item.customer_id) === customerCaseFilter.value)); const selectedCaseVisits = computed(() => visits.value.filter((item) => String(item.case_id) === String(selectedRow.value?.id || "")));
function unwrap(response: any): any { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
function rowsOf(response: any): Row[] { const data = unwrap(response); return Array.isArray(data) ? data : Array.isArray(data?.items) ? data.items : []; }
function statusLabel(value: unknown) { const key = String(value || ""); return statusLabels[key] || key || "-"; }
function tagType(value: unknown): "primary" | "success" | "warning" | "danger" | "info" { return ({ open: "warning", assigned: "primary", in_progress: "primary", resolved: "success", closed: "info", cancelled: "danger", reopened: "warning", active: "success", maintenance: "warning", retired: "info", completed: "success" } as Record<string, any>)[String(value)] || "info"; }
function assetLabel(assetId: unknown) { const asset = assets.value.find((item) => String(item.id) === String(assetId || "")); return asset ? `${asset.asset_code} · ${asset.asset_name}` : String(assetId || "-"); }
function customerLabel(customerId: unknown) { return customers.value.find((item) => item.value === String(customerId || ""))?.label || String(customerId || "-"); }
function ownerLabel(ownerId: unknown) { return assignees.value.find((item) => item.value === String(ownerId || ""))?.label || String(ownerId || "未派工"); }
function serviceTypeLabel(value: unknown) { return serviceTypeLabels[String(value)] || String(value || "-"); } function priorityLabel(value: unknown) { return priorityLabels[String(value)] || String(value || "-"); } function isOverdue(row: Row) { return row.sla_status === "overdue"; }

async function load() { loading.value = true; try { const results = await Promise.all([listAssets(), listAssetWorkOrders(), listServiceCases(), listMaintenancePlans(), listServiceContracts(), listEamAssignees(), loadOptions(["customers"])]); assets.value = rowsOf(results[0]); workOrders.value = rowsOf(results[1]); cases.value = rowsOf(results[2]); plans.value = rowsOf(results[3]); contracts.value = rowsOf(results[4]); assignees.value = rowsOf(results[5]).map((item) => ({ value: String(item.id), label: `${item.display_name || item.username}（${item.username}）` })); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "资产与售后服务加载失败"); } finally { loading.value = false; } }
function resetAssetForm() { Object.assign(assetForm, { asset_code: "", asset_name: "", serial_no: "", location: "", next_maintenance_date: "", status: "active", retirement_reason: "" }); editingAssetId.value = ""; } function resetPlanForm() { Object.assign(planForm, { asset_id: assets.value[0]?.id || "", name: "", interval_days: 30, next_due: "" }); } function resetWorkForm() { Object.assign(workForm, { asset_id: assets.value[0]?.id || "", service_type: "repair", description: "", due_date: "", owner_id: "", maintenance_plan_id: "" }); } function resetCaseForm() { Object.assign(caseForm, { customer_id: "", contract_id: "", title: "", priority: "normal", due_date: "", owner_id: "", sla_hours: 48 }); customerCaseFilter.value = ""; }
function openAsset() { resetAssetForm(); dialog.value = "asset"; } function openAssetEdit(row: Row) { editingAssetId.value = String(row.id); Object.assign(assetForm, { asset_code: row.asset_code || "", asset_name: row.asset_name || "", serial_no: row.serial_no || "", location: row.location || "", next_maintenance_date: row.next_maintenance_date || "", status: row.status || "active", retirement_reason: row.retirement_reason || "" }); dialog.value = "asset"; } function openPlan() { resetPlanForm(); dialog.value = "plan"; } function openWorkCreate() { resetWorkForm(); dialog.value = "work-create"; } function openCaseCreate() { resetCaseForm(); dialog.value = "case-create"; }
async function saveAsset() { if (!assetForm.asset_code || !assetForm.asset_name) return ElMessage.warning("请填写资产编码和名称"); saving.value = true; try { if (editingAssetId.value) unwrap(await updateAsset(editingAssetId.value, { asset_name: assetForm.asset_name, serial_no: assetForm.serial_no, location: assetForm.location, next_maintenance_date: assetForm.next_maintenance_date || null, status: assetForm.status, retirement_reason: assetForm.retirement_reason || null })); else unwrap(await createAsset({ asset_code: assetForm.asset_code, asset_name: assetForm.asset_name, serial_no: assetForm.serial_no, location: assetForm.location, next_maintenance_date: assetForm.next_maintenance_date || null })); ElMessage.success(editingAssetId.value ? "资产已更新" : "资产已创建"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "资产保存失败"); } finally { saving.value = false; } }
async function changeAssetStatus(row: Row, status: string) { actionLoading.value = String(row.id); try { unwrap(await updateAsset(String(row.id), { status })); ElMessage.success(`资产已${statusLabel(status)}`); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "资产状态更新失败"); } finally { actionLoading.value = null; } }
async function savePlan() { if (!planForm.asset_id || !planForm.name || !planForm.next_due) return ElMessage.warning("请填写资产、计划名称和下次到期日"); saving.value = true; try { unwrap(await createMaintenancePlan(planForm)); ElMessage.success("保养计划已创建"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保养计划创建失败"); } finally { saving.value = false; } }
async function generatePlanWorkOrder(row: Row) { actionLoading.value = String(row.id); try { unwrap(await generateMaintenanceWorkOrder(String(row.id))); ElMessage.success("保养工单已生成"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保养工单生成失败"); } finally { actionLoading.value = null; } }
async function saveWorkCreate() { if (!workForm.asset_id || !workForm.description) return ElMessage.warning("请选择资产并填写工单描述"); saving.value = true; try { unwrap(await createAssetWorkOrder({ ...workForm, owner_id: workForm.owner_id || null, maintenance_plan_id: workForm.maintenance_plan_id || null })); ElMessage.success("维修工单已创建"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "维修工单创建失败"); } finally { saving.value = false; } }
function openWorkProcess(row: Row, target = "") { selectedRow.value = row; transitionTarget.value = target; Object.assign(workProcessForm, { owner_id: row.owner_id || "", resolution: row.resolution || "", actual_hours: Number(row.actual_hours || 0), parts_cost: Number(row.parts_cost || 0), labor_cost: Number(row.labor_cost || 0) }); dialog.value = "work-process"; }
async function saveWorkProcess() { if (!selectedRow.value) return; saving.value = true; try { if (!transitionTarget.value || !["closed", "cancelled"].includes(String(selectedRow.value.status))) unwrap(await updateAssetWorkOrder(String(selectedRow.value.id), { ...workProcessForm, owner_id: workProcessForm.owner_id || null })); if (transitionTarget.value) unwrap(await transitionAssetWorkOrder(String(selectedRow.value.id), transitionTarget.value, { resolution: workProcessForm.resolution || null, actual_hours: workProcessForm.actual_hours, parts_cost: workProcessForm.parts_cost, labor_cost: workProcessForm.labor_cost })); ElMessage.success(transitionTarget.value ? `工单已${statusLabel(transitionTarget.value)}` : "工单信息已保存"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "维修工单处理失败"); } finally { saving.value = false; } }
async function saveCaseCreate() { if (!caseForm.customer_id || !caseForm.title) return ElMessage.warning("请选择客户并填写服务问题"); saving.value = true; try { unwrap(await createServiceCase({ ...caseForm, contract_id: caseForm.contract_id || null, owner_id: caseForm.owner_id || null })); ElMessage.success("服务工单已创建"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "服务工单创建失败"); } finally { saving.value = false; } }
function openCaseProcess(row: Row, target = "") { selectedRow.value = row; transitionTarget.value = target; Object.assign(caseProcessForm, { owner_id: row.owner_id || "", resolution: row.resolution || "", customer_feedback: row.customer_feedback || "", satisfaction_score: row.satisfaction_score || undefined }); dialog.value = "case-process"; loadVisits(String(row.id)); }
async function saveCaseProcess() { if (!selectedRow.value) return; saving.value = true; try { if (!transitionTarget.value || !["closed", "cancelled"].includes(String(selectedRow.value.status))) unwrap(await updateServiceCase(String(selectedRow.value.id), { ...caseProcessForm, owner_id: caseProcessForm.owner_id || null })); if (transitionTarget.value) unwrap(await transitionServiceCase(String(selectedRow.value.id), transitionTarget.value, { resolution: caseProcessForm.resolution || null, customer_feedback: caseProcessForm.customer_feedback || null, satisfaction_score: caseProcessForm.satisfaction_score || null })); ElMessage.success(transitionTarget.value ? `服务工单已${statusLabel(transitionTarget.value)}` : "服务工单信息已保存"); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "服务工单处理失败"); } finally { saving.value = false; } }
async function loadVisits(caseId: string) { try { visits.value = rowsOf(await listServiceVisits(caseId)); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "回访记录加载失败"); } }
function openVisit(row: Row) { selectedRow.value = row; Object.assign(visitForm, { case_id: row.id, scheduled_at: "", technician_id: row.owner_id || "", notes: "" }); Object.assign(visitUpdateForm, { id: "", status: "scheduled", outcome: "", feedback_score: undefined }); loadVisits(String(row.id)); dialog.value = "visit"; }
async function saveVisit() { if (!visitForm.scheduled_at || !visitForm.technician_id) return ElMessage.warning("请选择回访时间和执行人"); saving.value = true; try { unwrap(await createServiceVisit(visitForm)); ElMessage.success("回访已安排"); await loadVisits(String(visitForm.case_id)); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "回访安排失败"); } finally { saving.value = false; } }
async function completeVisit() { if (!visitUpdateForm.id || !visitUpdateForm.outcome) return ElMessage.warning("请填写回访结果"); saving.value = true; try { unwrap(await updateServiceVisit(visitUpdateForm.id, { status: visitUpdateForm.status, outcome: visitUpdateForm.outcome, feedback_score: visitUpdateForm.feedback_score })); ElMessage.success("回访结果已保存"); await loadVisits(String(selectedRow.value?.id)); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "回访结果保存失败"); } finally { saving.value = false; } }
function openDocument(type: string, row: Row) { documentType.value = type; documentId.value = String(row.id); documentVisible.value = true; }
onMounted(load);
</script>

<template>
  <section class="page-stack">
    <header class="page-heading"><div><small>EAM / AFTER-SALES SERVICE</small><h1>资产与售后服务中心</h1><p>资产台账、保养维修、服务工单共用责任人、期限与状态闭环。</p></div><el-space><el-button type="primary" @click="openAsset">新增资产</el-button><el-button @click="openWorkCreate">新建维修工单</el-button><el-button @click="openCaseCreate">新建服务工单</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header>
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="资产台账" name="assets"><el-table v-loading="loading" :data="assetRows" stripe><el-table-column prop="asset_code" label="资产编码" width="145" /><el-table-column prop="asset_name" label="名称" min-width="180" /><el-table-column prop="serial_no" label="序列号" /><el-table-column prop="location" label="位置" /><el-table-column prop="next_maintenance_date" label="下次保养" /><el-table-column label="状态"><template #default="scope"><el-tag :type="tagType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="关联闭环" min-width="150"><template #default="scope">{{ scope.row.open_work_order_count || 0 }} 个处理中 / {{ scope.row.maintenance_plan_count || 0 }} 个计划</template></el-table-column><el-table-column label="操作" width="250"><template #default="scope"><el-button link type="primary" @click="openAssetEdit(scope.row)">编辑</el-button><el-button v-if="scope.row.status === 'active'" link type="warning" :loading="actionLoading === scope.row.id" @click="changeAssetStatus(scope.row, 'maintenance')">标记保养</el-button><el-button v-if="scope.row.status !== 'retired'" link type="danger" :loading="actionLoading === scope.row.id" @click="changeAssetStatus(scope.row, 'retired')">报废</el-button><el-button v-if="scope.row.status === 'retired'" link type="success" @click="changeAssetStatus(scope.row, 'active')">恢复在用</el-button></template></el-table-column></el-table><ClientPagination v-model:page="assetPage" v-model:page-size="assetPageSize" :total="assetTotal" @update:page-size="updateAssetPageSize" /><el-card shadow="never" class="sub-card"><template #header><div class="card-heading"><span>保养计划与执行</span><el-button type="primary" plain @click="openPlan">新建保养计划</el-button></div></template><el-table :data="plans" stripe><el-table-column label="资产" min-width="190"><template #default="scope">{{ assetLabel(scope.row.asset_id) }}</template></el-table-column><el-table-column prop="name" label="计划名称" /><el-table-column prop="interval_days" label="周期（天）" width="110" /><el-table-column prop="next_due" label="下次到期" width="120" /><el-table-column label="状态"><template #default="scope"><el-tag :type="tagType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="scope"><el-button link type="primary" :loading="actionLoading === scope.row.id" @click="generatePlanWorkOrder(scope.row)">生成工单</el-button></template></el-table-column></el-table><template #footer><span class="muted">生成的保养工单关闭后会自动推进下一次到期日，并回写资产下次保养日期。</span></template></el-card></el-tab-pane>
      <el-tab-pane label="维修工单" name="work-orders"><el-table v-loading="loading" :data="workOrderRows" stripe><el-table-column prop="work_order_no" label="工单号" width="190" /><el-table-column label="资产" min-width="180"><template #default="scope">{{ assetLabel(scope.row.asset_id) }}</template></el-table-column><el-table-column label="类型" width="90"><template #default="scope">{{ serviceTypeLabel(scope.row.service_type) }}</template></el-table-column><el-table-column label="责任人" width="140"><template #default="scope">{{ ownerLabel(scope.row.owner_id) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="tagType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column prop="due_date" label="期限" width="120" /><el-table-column label="成本" width="130"><template #default="scope">¥{{ Number(scope.row.parts_cost || 0) + Number(scope.row.labor_cost || 0) }}</template></el-table-column><el-table-column label="操作" min-width="280"><template #default="scope"><el-button v-for="item in workTransitions[scope.row.status] || []" :key="item.to" link :type="item.type" @click="openWorkProcess(scope.row, item.to)">{{ item.label }}</el-button><el-button link type="primary" @click="openWorkProcess(scope.row)">处理</el-button><el-button link @click="openDocument('eam_work_order', scope.row)">详情</el-button></template></el-table-column></el-table><ClientPagination v-model:page="workOrderPage" v-model:page-size="workOrderPageSize" :total="workOrderTotal" @update:page-size="updateWorkOrderPageSize" /></el-tab-pane>
      <el-tab-pane label="服务工单" name="service-cases"><el-table v-loading="loading" :data="caseRows" stripe><el-table-column prop="case_no" label="服务单号" width="190" /><el-table-column label="客户" min-width="180"><template #default="scope">{{ customerLabel(scope.row.customer_id) }}</template></el-table-column><el-table-column prop="title" label="问题" min-width="190" /><el-table-column label="优先级" width="90"><template #default="scope">{{ priorityLabel(scope.row.priority) }}</template></el-table-column><el-table-column label="责任人" width="140"><template #default="scope">{{ ownerLabel(scope.row.owner_id) }}</template></el-table-column><el-table-column label="SLA" width="110"><template #default="scope"><el-tag :type="isOverdue(scope.row) ? 'danger' : 'success'">{{ isOverdue(scope.row) ? '已逾期' : 'SLA内' }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="tagType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column prop="due_date" label="SLA到期" width="120" /><el-table-column label="操作" min-width="320"><template #default="scope"><el-button v-for="item in caseTransitions[scope.row.status] || []" :key="item.to" link :type="item.type" @click="openCaseProcess(scope.row, item.to)">{{ item.label }}</el-button><el-button link type="primary" @click="openCaseProcess(scope.row)">处理</el-button><el-button link type="warning" @click="openVisit(scope.row)">回访</el-button><el-button link @click="openDocument('svc_case', scope.row)">详情</el-button></template></el-table-column></el-table><ClientPagination v-model:page="casePage" v-model:page-size="casePageSize" :total="caseTotal" @update:page-size="updateCasePageSize" /></el-tab-pane>
    </el-tabs>
    <el-dialog :model-value="dialog === 'asset'" :title="editingAssetId ? '编辑资产' : '新增资产'" width="560px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="资产编码" required><el-input v-model="assetForm.asset_code" :disabled="Boolean(editingAssetId)" /></el-form-item><el-form-item label="资产名称" required><el-input v-model="assetForm.asset_name" /></el-form-item><el-form-item label="序列号"><el-input v-model="assetForm.serial_no" /></el-form-item><el-form-item label="位置"><el-input v-model="assetForm.location" /></el-form-item><el-form-item label="下次保养"><el-date-picker v-model="assetForm.next_maintenance_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item v-if="editingAssetId" label="状态"><el-select v-model="assetForm.status"><el-option label="在用" value="active" /><el-option label="保养中" value="maintenance" /><el-option label="已报废" value="retired" /></el-select></el-form-item><el-form-item v-if="editingAssetId && assetForm.status === 'retired'" label="报废原因"><el-input v-model="assetForm.retirement_reason" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveAsset">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'plan'" title="新建保养计划" width="560px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="资产" required><el-select v-model="planForm.asset_id" filterable style="width: 100%"><el-option v-for="item in assets" :key="item.id" :label="`${item.asset_code} · ${item.asset_name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="计划名称" required><el-input v-model="planForm.name" /></el-form-item><el-form-item label="周期（天）" required><el-input-number v-model="planForm.interval_days" :min="1" :max="3650" /></el-form-item><el-form-item label="下次到期" required><el-date-picker v-model="planForm.next_due" value-format="YYYY-MM-DD" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="savePlan">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'work-create'" title="新建维修工单" width="600px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="资产" required><el-select v-model="workForm.asset_id" filterable style="width: 100%"><el-option v-for="item in assets.filter((asset) => asset.status !== 'retired')" :key="item.id" :label="`${item.asset_code} · ${item.asset_name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="类型"><el-select v-model="workForm.service_type"><el-option label="维修" value="repair" /><el-option label="保养" value="maintenance" /><el-option label="点检" value="inspection" /></el-select></el-form-item><el-form-item label="责任人"><el-select v-model="workForm.owner_id" filterable clearable style="width: 100%"><el-option v-for="item in assignees" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="期限"><el-date-picker v-model="workForm.due_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="关联计划"><el-select v-model="workForm.maintenance_plan_id" clearable style="width: 100%"><el-option v-for="item in plans.filter((plan) => String(plan.asset_id) === String(workForm.asset_id))" :key="item.id" :label="`${item.name}（${item.next_due}）`" :value="item.id" /></el-select></el-form-item><el-form-item label="描述" required><el-input v-model="workForm.description" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveWorkCreate">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'work-process'" :title="transitionTarget ? `维修工单：${statusLabel(transitionTarget)}` : '维修工单处理'" width="620px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="责任人"><el-select v-model="workProcessForm.owner_id" filterable clearable style="width: 100%"><el-option v-for="item in assignees" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="处理结果"><el-input v-model="workProcessForm.resolution" type="textarea" :rows="3" placeholder="解决或关闭工单时必填" /></el-form-item><el-form-item label="实际工时"><el-input-number v-model="workProcessForm.actual_hours" :min="0" :precision="2" /></el-form-item><el-form-item label="备件成本"><el-input-number v-model="workProcessForm.parts_cost" :min="0" :precision="2" /></el-form-item><el-form-item label="人工成本"><el-input-number v-model="workProcessForm.labor_cost" :min="0" :precision="2" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveWorkProcess">保存{{ transitionTarget ? '并流转' : '' }}</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'case-create'" title="新建服务工单" width="620px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="客户" required><el-select v-model="caseForm.customer_id" filterable clearable style="width: 100%" @change="customerCaseFilter = caseForm.customer_id; caseForm.contract_id = ''"><el-option v-for="item in customers" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="服务合同"><el-select v-model="caseForm.contract_id" clearable style="width: 100%"><el-option v-for="item in filteredContracts" :key="item.id" :label="`${item.contract_no}（${item.start_date} 至 ${item.end_date}）`" :value="item.id" /></el-select></el-form-item><el-form-item label="问题标题" required><el-input v-model="caseForm.title" /></el-form-item><el-form-item label="优先级"><el-select v-model="caseForm.priority"><el-option v-for="(label, value) in priorityLabels" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="责任人"><el-select v-model="caseForm.owner_id" filterable clearable style="width: 100%"><el-option v-for="item in assignees" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="SLA时限"><el-input-number v-model="caseForm.sla_hours" :min="1" :max="8760" /><span class="field-suffix">小时</span></el-form-item><el-form-item label="SLA到期"><el-date-picker v-model="caseForm.due_date" value-format="YYYY-MM-DD" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveCaseCreate">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'case-process'" :title="transitionTarget ? `服务工单：${statusLabel(transitionTarget)}` : '服务工单处理'" width="620px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="责任人"><el-select v-model="caseProcessForm.owner_id" filterable clearable style="width: 100%"><el-option v-for="item in assignees" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="解决方案"><el-input v-model="caseProcessForm.resolution" type="textarea" :rows="3" placeholder="解决或关闭工单时必填" /></el-form-item><el-form-item label="客户反馈"><el-input v-model="caseProcessForm.customer_feedback" type="textarea" :rows="2" /></el-form-item><el-form-item label="满意度"><el-rate v-model="caseProcessForm.satisfaction_score" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveCaseProcess">保存{{ transitionTarget ? '并流转' : '' }}</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'visit'" title="服务回访闭环" width="760px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-table :data="selectedCaseVisits" size="small" stripe><el-table-column prop="scheduled_at" label="计划时间" width="170" /><el-table-column label="执行人"><template #default="scope">{{ ownerLabel(scope.row.technician_id) }}</template></el-table-column><el-table-column label="状态"><template #default="scope"><el-tag :type="tagType(scope.row.status)">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column prop="outcome" label="结果" min-width="180" /><el-table-column label="操作" width="90"><template #default="scope"><el-button v-if="scope.row.status !== 'completed' && scope.row.status !== 'cancelled'" link type="primary" @click="Object.assign(visitUpdateForm, { id: scope.row.id, status: 'completed', outcome: scope.row.outcome || '', feedback_score: scope.row.feedback_score || undefined })">完成</el-button></template></el-table-column></el-table><el-divider /><el-form label-width="100px"><el-form-item label="回访时间" required><el-date-picker v-model="visitForm.scheduled_at" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item><el-form-item label="执行人" required><el-select v-model="visitForm.technician_id" filterable style="width: 100%"><el-option v-for="item in assignees" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="回访备注"><el-input v-model="visitForm.notes" type="textarea" /></el-form-item><el-form-item v-if="visitUpdateForm.id" label="回访结果" required><el-input v-model="visitUpdateForm.outcome" type="textarea" /></el-form-item><el-form-item v-if="visitUpdateForm.id" label="满意度"><el-rate v-model="visitUpdateForm.feedback_score" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">关闭</el-button><el-button v-if="visitUpdateForm.id" type="success" :loading="saving" @click="completeVisit">保存回访结果</el-button><el-button type="primary" :loading="saving" @click="saveVisit">安排回访</el-button></template></el-dialog>
    <DocumentWorkbench v-model:visible="documentVisible" :business-type="documentType" :business-id="documentId" />
  </section>
</template>

<style scoped>
.page-stack { display: flex; flex-direction: column; gap: 16px; }.page-heading { display: flex; justify-content: space-between; align-items: flex-end; gap: 16px; }.page-heading small { color: var(--erp-muted-text); letter-spacing: .08em; }.page-heading h1 { margin: 4px 0; }.page-heading p { margin: 0; color: var(--erp-muted-text); }.sub-card { margin-top: 18px; }.card-heading { display: flex; justify-content: space-between; align-items: center; }.muted { color: var(--erp-muted-text); }.field-suffix { margin-left: 8px; color: var(--erp-muted-text); }
</style>
