<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { createShipment, listOcrDocuments, listShipments, processOcrDocument, transitionShipment } from "../../api/advanced";
import { approveBudget, createBudget, createCashForecast, listBudgets, listCashForecasts, listFinanceAccounts } from "../../api/finance";
import { useClientPagination } from "../../composables/useClientPagination";
import { statusLabel, tagTypeOf } from "../../utils/labels";
type Row = Record<string, any>;
const shipments = ref<Row[]>([]); const ocrRows = ref<Row[]>([]); const budgets = ref<Row[]>([]); const forecasts = ref<Row[]>([]); const accounts = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const dialog = ref("");
const activeTab = ref("transport");
const shipmentFilters = reactive({ shipment_no: "", carrier_name: "", origin: "", destination: "", dateRange: [] as string[], status: "" });
const filteredShipments = computed(() => shipments.value.filter((row) => (!shipmentFilters.shipment_no || String(row.shipment_no || "").includes(shipmentFilters.shipment_no)) && (!shipmentFilters.carrier_name || String(row.carrier_name || "").includes(shipmentFilters.carrier_name)) && (!shipmentFilters.origin || String(row.origin || "").includes(shipmentFilters.origin)) && (!shipmentFilters.destination || String(row.destination || "").includes(shipmentFilters.destination)) && (!shipmentFilters.status || row.status === shipmentFilters.status) && (!shipmentFilters.dateRange.length || (String(row.planned_date || "") >= shipmentFilters.dateRange[0] && String(row.planned_date || "") <= shipmentFilters.dateRange[1]))));
const { pagedRows: shipmentRows, page: shipmentPage, pageSize: shipmentPageSize, total: shipmentTotal, updatePageSize: updateShipmentPageSize } = useClientPagination(filteredShipments);
const shipmentForm = reactive({ carrier_name: "", origin: "", destination: "", planned_date: "", freight_amount: 0, source_type: "", source_id: "", note: "" }); const ocrForm = reactive({ document_type: "invoice", source_file: "manual.txt", raw_text: "" }); const budgetForm = reactive({ budget_period: new Date().toISOString().slice(0, 7), account_code: "", department_id: "", budget_amount: 0, note: "" }); const forecastForm = reactive({ forecast_date: new Date().toISOString().slice(0, 10), inflow_amount: 0, outflow_amount: 0, source: "manual", note: "" });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
async function load() { loading.value = true; try { const [shipment, ocr, budget, forecast, account] = await Promise.all([listShipments().then(unwrap), listOcrDocuments().then(unwrap), listBudgets().then(unwrap), listCashForecasts().then(unwrap), listFinanceAccounts({ page: 1, page_size: 200 }).then(unwrap)]); shipments.value = shipment || []; ocrRows.value = ocr || []; budgets.value = budget?.items || []; forecasts.value = forecast?.items || []; accounts.value = account?.items || []; if (!budgetForm.account_code) budgetForm.account_code = accounts.value[0]?.code || ""; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "高级运营加载失败"); } finally { loading.value = false; } }
function open(kind: string) { dialog.value = kind; if (kind === "shipment") Object.assign(shipmentForm, { carrier_name: "", origin: "", destination: "", planned_date: "", freight_amount: 0, source_type: "", source_id: "", note: "" }); if (kind === "ocr") Object.assign(ocrForm, { document_type: "invoice", source_file: "manual.txt", raw_text: "" }); }
async function saveAction(action: () => Promise<any>, message: string) { saving.value = true; try { unwrap(await action()); ElMessage.success(message); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } finally { saving.value = false; } }
async function saveShipment() { if (!shipmentForm.carrier_name || !shipmentForm.origin || !shipmentForm.destination || !shipmentForm.planned_date) return ElMessage.warning("请填写承运商、起点、终点和计划日期"); await saveAction(() => createShipment(shipmentForm), "运输单已创建"); }
async function changeShipment(row: Row, status: string) { await saveAction(() => transitionShipment(row.id, { status }), "运输状态已更新"); }
async function processOcr() { if (!ocrForm.raw_text.trim()) return ElMessage.warning("请粘贴待识别文本"); await saveAction(() => processOcrDocument(ocrForm), "OCR 识别已完成"); }
async function saveBudget() { if (!budgetForm.account_code || budgetForm.budget_amount < 0) return ElMessage.warning("请选择预算科目并填写金额"); await saveAction(() => createBudget(budgetForm), "预算已保存"); }
async function saveForecast() { if (forecastForm.inflow_amount < 0 || forecastForm.outflow_amount < 0) return ElMessage.warning("预测金额不能为负数"); await saveAction(() => createCashForecast(forecastForm), "现金预测已保存"); }
async function approve(row: Row) { await saveAction(() => approveBudget(row.id), "预算已审批"); }
onMounted(load);
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>OPERATIONS / TMS / OCR / FORECAST</small><h1>运输与预测</h1><p>运输状态、单据识别、预算执行和现金预测统一保留操作记录。</p></div><el-button :loading="loading" @click="load">刷新</el-button></header>
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="运输管理" name="transport"><div class="toolbar"><el-input v-model="shipmentFilters.shipment_no" clearable placeholder="运输单号" /><el-input v-model="shipmentFilters.carrier_name" clearable placeholder="承运商" /><el-input v-model="shipmentFilters.origin" clearable placeholder="起点" /><el-input v-model="shipmentFilters.destination" clearable placeholder="终点" /><el-date-picker v-model="shipmentFilters.dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="计划开始" end-placeholder="计划结束" /><el-select v-model="shipmentFilters.status" clearable placeholder="全部状态"><el-option label="草稿" value="draft" /><el-option label="已计划" value="planned" /><el-option label="已发运" value="dispatched" /><el-option label="运输中" value="in_transit" /><el-option label="已签收" value="delivered" /></el-select><el-button type="primary" @click="open('shipment')">新建运输单</el-button></div><el-table :data="shipmentRows" stripe><el-table-column prop="shipment_no" label="运输单号" /><el-table-column prop="carrier_name" label="承运商" /><el-table-column prop="origin" label="起点" /><el-table-column prop="destination" label="终点" /><el-table-column prop="planned_date" label="计划日期" /><el-table-column prop="freight_amount" label="运费" /><el-table-column label="状态"><template #default="scope"><el-tag :type="tagTypeOf(scope.row.status)" effect="light">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status === 'draft'" link type="primary" @click="changeShipment(scope.row, 'planned')">计划</el-button><el-button v-if="scope.row.status === 'planned'" link type="primary" @click="changeShipment(scope.row, 'dispatched')">发运</el-button><el-button v-if="['dispatched','in_transit'].includes(scope.row.status)" link type="success" @click="changeShipment(scope.row, 'delivered')">签收</el-button></template></el-table-column></el-table><ClientPagination v-model:page="shipmentPage" v-model:page-size="shipmentPageSize" :total="shipmentTotal" @update:page-size="updateShipmentPageSize" /></el-tab-pane>
      <el-tab-pane label="OCR 识别" name="ocr"><div class="toolbar"><el-button type="primary" @click="open('ocr')">新建识别任务</el-button></div><el-table :data="ocrRows" stripe><el-table-column prop="document_type" label="单据类型" /><el-table-column prop="source_file" label="来源文件" /><el-table-column prop="extracted_json" label="识别结果" /><el-table-column prop="confidence" label="置信度" /><el-table-column prop="status" label="状态" /></el-table></el-tab-pane>
      <el-tab-pane label="预算执行" name="budget"><div class="toolbar"><el-input v-model="budgetForm.budget_period" placeholder="YYYY-MM" /><el-select v-model="budgetForm.account_code" placeholder="预算科目"><el-option v-for="item in accounts" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.code" /></el-select><el-input-number v-model="budgetForm.budget_amount" :min="0" /><el-button type="primary" @click="saveBudget">保存预算</el-button></div><el-table :data="budgets" stripe><el-table-column prop="budget_period" label="期间" /><el-table-column prop="account_code" label="科目" /><el-table-column prop="budget_amount" label="预算" /><el-table-column prop="actual_amount" label="实际" /><el-table-column prop="variance_amount" label="差异" /><el-table-column prop="status" label="状态" /><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status === 'draft'" link type="primary" @click="approve(scope.row)">审批</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="现金预测" name="forecast"><div class="toolbar"><el-date-picker v-model="forecastForm.forecast_date" type="date" value-format="YYYY-MM-DD" /><el-input-number v-model="forecastForm.inflow_amount" :min="0" placeholder="流入" /><el-input-number v-model="forecastForm.outflow_amount" :min="0" placeholder="流出" /><el-input v-model="forecastForm.source" placeholder="来源" /><el-button type="primary" @click="saveForecast">保存预测</el-button></div><el-table :data="forecasts" stripe><el-table-column prop="forecast_date" label="日期" /><el-table-column prop="inflow_amount" label="流入" /><el-table-column prop="outflow_amount" label="流出" /><el-table-column prop="net_amount" label="净额" /><el-table-column prop="source" label="来源" /></el-table></el-tab-pane>
    </el-tabs>
    <el-dialog :model-value="dialog === 'shipment'" title="新建运输单" width="600px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="承运商" required><el-input v-model="shipmentForm.carrier_name" /></el-form-item><el-form-item label="起点" required><el-input v-model="shipmentForm.origin" /></el-form-item><el-form-item label="终点" required><el-input v-model="shipmentForm.destination" /></el-form-item><el-form-item label="计划日期" required><el-date-picker v-model="shipmentForm.planned_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="运费"><el-input-number v-model="shipmentForm.freight_amount" :min="0" /></el-form-item><el-form-item label="来源单据"><el-input v-model="shipmentForm.source_id" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveShipment">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'ocr'" title="OCR 识别任务" width="650px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="单据类型"><el-select v-model="ocrForm.document_type"><el-option label="发票" value="invoice" /><el-option label="采购单" value="purchase_order" /><el-option label="收货单" value="receipt" /></el-select></el-form-item><el-form-item label="来源文件"><el-input v-model="ocrForm.source_file" /></el-form-item><el-form-item label="待识别文本" required><el-input v-model="ocrForm.raw_text" type="textarea" :rows="8" placeholder="例如：单号 PO-001，日期 2026-08-15，金额 123.45" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="processOcr">开始识别</el-button></template></el-dialog>
  </section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:4px 0 0;color:var(--erp-muted-text)}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.toolbar>*{max-width:240px}</style>
