<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { createApiClient, listApiClients, setApiClientStatus } from "../../api/platform";

type Row = Record<string, any>;
const rows = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const visible = ref(false); const key = ref(""); const scopes = ref("crm:read"); const secret = ref("");
async function load() { loading.value = true; try { const response = await listApiClients(); if (response.data.code !== 0) throw new Error(response.data.msg); rows.value = Array.isArray(response.data?.data) ? response.data.data : []; } catch (error) { rows.value = []; ElMessage.error(error instanceof Error ? error.message : "API 客户端列表加载失败"); } finally { loading.value = false; } }
function openCreate() { key.value = ""; scopes.value = "crm:read"; secret.value = ""; visible.value = true; }
async function create() { const clientKey = key.value.trim(); const clientScopes = scopes.value.split(",").map((item) => item.trim()).filter(Boolean); if (!clientKey || !clientScopes.length) { ElMessage.warning("请填写客户端 Key 和至少一个权限范围"); return; } saving.value = true; try { const response = await createApiClient({ client_key: clientKey, scopes: clientScopes }); if (response.data.code !== 0) throw new Error(response.data.msg); secret.value = response.data.data?.secret || ""; ElMessage.success("客户端已创建，请立即保存 Secret"); visible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "客户端创建失败"); } finally { saving.value = false; } }
async function toggle(row: Row) { const next = row.status === "active" ? "inactive" : "active"; try { await ElMessageBox.confirm(`确认${next === "active" ? "启用" : "停用"}客户端“${row.client_key}”吗？`, "状态确认", { type: "warning" }); saving.value = true; const response = await setApiClientStatus(row.id, next); if (response.data.code !== 0) throw new Error(response.data.msg); await load(); } catch (error: any) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "客户端状态更新失败"); } finally { saving.value = false; } }
onMounted(load);
</script>

<template>
  <section class="page-stack"><el-page-header content="OpenAPI 客户端" /><el-space><el-button type="primary" @click="openCreate">创建客户端</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space><el-alert v-if="secret" :title="`新客户端 Secret（仅本次返回）：${secret}`" type="warning" show-icon /><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="client_key" label="客户端 Key" min-width="200" /><el-table-column label="权限范围" min-width="240"><template #default="scope">{{ (scope.row.scopes || []).join(", ") }}</template></el-table-column><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="created_at" label="创建时间" min-width="180" /><el-table-column label="操作" width="110"><template #default="scope"><el-button link :type="scope.row.status === 'active' ? 'danger' : 'success'" :loading="saving" @click="toggle(scope.row)">{{ scope.row.status === "active" ? "停用" : "启用" }}</el-button></template></el-table-column><template #empty><el-empty description="暂无 API 客户端" /></template></el-table><el-dialog v-model="visible" title="创建 OpenAPI 客户端" width="520px"><el-form label-width="100px"><el-form-item label="客户端 Key" required><el-input v-model="key" placeholder="例如 erp-integration" /></el-form-item><el-form-item label="权限范围" required><el-input v-model="scopes" placeholder="多个范围用逗号分隔，如 crm:read,sales:read" /></el-form-item></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog></section>
</template>

<style scoped>.page-stack { display: flex; flex-direction: column; gap: 16px; }</style>
