<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import { createSubscription, dispatchEvent, listEvents, listSubscriptions, processDueEvents, setSubscriptionStatus } from "../../api/platform";
import { useClientPagination } from "../../composables/useClientPagination";

type Row = Record<string, any>;
const subscriptions = ref<Row[]>([]); const events = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const visible = ref(false); const secret = ref("");
const { pagedRows: subscriptionRows, page: subscriptionPage, pageSize: subscriptionPageSize, total: subscriptionTotal, updatePageSize: updateSubscriptionPageSize } = useClientPagination(subscriptions);
const { pagedRows: eventRows, page: eventPage, pageSize: eventPageSize, total: eventTotal, updatePageSize: updateEventPageSize } = useClientPagination(events);
const form = ref({ name: "", endpoint_url: "", event_types: "*" });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
async function load() { loading.value = true; try { const [subscriptionData, eventData] = await Promise.all([listSubscriptions(), listEvents()]); subscriptions.value = unwrap(subscriptionData) || []; events.value = unwrap(eventData) || []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "平台事件加载失败"); } finally { loading.value = false; } }
function openCreate() { form.value = { name: "", endpoint_url: "", event_types: "*" }; secret.value = ""; visible.value = true; }
async function save() { saving.value = true; try { const data = unwrap(await createSubscription({ name: form.value.name.trim(), endpoint_url: form.value.endpoint_url.trim(), event_types: form.value.event_types.split(",").map((item) => item.trim()).filter(Boolean) })); secret.value = data.secret || ""; visible.value = false; ElMessage.success("订阅已创建，请保存签名 Secret"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "订阅创建失败"); } finally { saving.value = false; } }
async function dispatch(row: Row) { try { unwrap(await dispatchEvent(String(row.id))); ElMessage.success("事件已投递"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "事件投递失败"); } }
async function processDue() { try { const result = unwrap(await processDueEvents()); ElMessage.success(`已处理 ${result.processed || 0} 个事件`); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "批量处理事件失败"); } }
async function toggleSubscription(row: Row) { try { unwrap(await setSubscriptionStatus(String(row.id), row.status === "active" ? "inactive" : "active")); ElMessage.success("订阅状态已更新"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "订阅状态更新失败"); } }
onMounted(load);
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>OPEN PLATFORM EVENTS</small><h1>事件订阅与投递</h1><p>为外部系统配置事件订阅，支持签名、投递结果、失败重试和死信处理。</p></div><el-space><el-button type="primary" @click="openCreate">新增订阅</el-button><el-button type="warning" :loading="loading" @click="processDue">处理到期事件</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header><el-alert v-if="secret" :title="`新订阅签名 Secret（仅本次返回）：${secret}`" type="warning" show-icon /><el-card v-loading="loading" shadow="never"><el-tabs><el-tab-pane label="订阅"><el-table :data="subscriptionRows" stripe><el-table-column prop="name" label="名称" /><el-table-column prop="endpoint_url" label="回调地址" min-width="280" /><el-table-column label="事件类型" min-width="180"><template #default="scope">{{ (scope.row.event_types || []).join(', ') }}</template></el-table-column><el-table-column prop="failure_count" label="连续失败" width="100" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="100"><template #default="scope"><el-button link :type="scope.row.status === 'active' ? 'danger' : 'success'" @click="toggleSubscription(scope.row)">{{ scope.row.status === "active" ? "停用" : "启用" }}</el-button></template></el-table-column><template #empty><el-empty description="暂无事件订阅" /></template></el-table><ClientPagination v-model:page="subscriptionPage" v-model:page-size="subscriptionPageSize" :total="subscriptionTotal" @update:page-size="updateSubscriptionPageSize" /></el-tab-pane><el-tab-pane label="事件出站"><el-table :data="eventRows" stripe><el-table-column prop="event_type" label="事件类型" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="retry_count" label="重试次数" width="110" /><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="primary" :disabled="scope.row.status === 'delivered' || scope.row.status === 'dead_letter'" @click="dispatch(scope.row)">投递</el-button></template></el-table-column><template #empty><el-empty description="暂无待投递事件" /></template></el-table><ClientPagination v-model:page="eventPage" v-model:page-size="eventPageSize" :total="eventTotal" @update:page-size="updateEventPageSize" /></el-tab-pane></el-tabs></el-card><el-dialog v-model="visible" title="新增事件订阅" width="560px"><el-form label-width="100px"><el-form-item label="名称" required><el-input v-model="form.name" placeholder="订单同步" /></el-form-item><el-form-item label="回调地址" required><el-input v-model="form.endpoint_url" placeholder="https://example.com/webhook" /></el-form-item><el-form-item label="事件类型" required><el-input v-model="form.event_types" placeholder="* 或 order.created, order.updated" /></el-form-item></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建</el-button></template></el-dialog></section>
</template>
<style scoped>.page-stack { display:flex; flex-direction:column; gap:16px; }.page-heading { display:flex; justify-content:space-between; align-items:flex-end; }.page-heading small { color:var(--erp-muted-text); letter-spacing:.08em; }.page-heading h1 { margin:4px 0; }.page-heading p { margin:0; color:var(--erp-muted-text); }</style>
