import { http } from "./http";

export const listCandidates = () => http.get("/advanced/hr/candidates");
export const createCandidate = (payload: unknown) => http.post("/advanced/hr/candidates", payload);
export const updateCandidate = (id: string, payload: unknown) => http.put(`/advanced/hr/candidates/${id}`, payload);
export const listLifecycle = (employeeId?: string) => http.get("/advanced/hr/lifecycle", { params: employeeId ? { employee_id: employeeId } : undefined });
export const createLifecycle = (payload: unknown) => http.post("/advanced/hr/lifecycle", payload);
export const listPerformance = (employeeId?: string) => http.get("/advanced/hr/performance", { params: employeeId ? { employee_id: employeeId } : undefined });
export const savePerformance = (payload: unknown) => http.post("/advanced/hr/performance", payload);
export const listBenefits = (employeeId?: string) => http.get("/advanced/hr/benefits", { params: employeeId ? { employee_id: employeeId } : undefined });
export const createBenefit = (payload: unknown) => http.post("/advanced/hr/benefits", payload);

export const listSpc = (materialId?: string) => http.get("/advanced/quality/spc", { params: materialId ? { material_id: materialId } : undefined });
export const createSpc = (payload: unknown) => http.post("/advanced/quality/spc", payload);
export const listSpcExceptions = (status?: string) => http.get("/advanced/quality/spc/exceptions", { params: status ? { status } : undefined });
export const getSpcException = (id: string) => http.get(`/advanced/quality/spc/exceptions/${id}`);
export const confirmSpcException = (id: string, payload: unknown) => http.put(`/advanced/quality/spc/exceptions/${id}/confirm`, payload);
export const saveSpcContainment = (id: string, payload: unknown) => http.put(`/advanced/quality/spc/exceptions/${id}/containment`, payload);
export const saveSpcRootCause = (id: string, payload: unknown) => http.put(`/advanced/quality/spc/exceptions/${id}/root-cause`, payload);
export const resumeSpcException = (id: string) => http.post(`/advanced/quality/spc/exceptions/${id}/resume`);
export const createSpcAction = (id: string, payload: unknown) => http.post(`/advanced/quality/spc/exceptions/${id}/actions`, payload);
export const completeSpcAction = (exceptionId: string, actionId: string, payload: unknown) => http.post(`/advanced/quality/spc/exceptions/${exceptionId}/actions/${actionId}/complete`, payload);
export const retestSpcException = (id: string, payload: unknown) => http.post(`/advanced/quality/spc/exceptions/${id}/retest`, payload);
export const closeSpcException = (id: string, payload: unknown) => http.post(`/advanced/quality/spc/exceptions/${id}/close`, payload);
export const listSupplierQuality = (supplierId?: string) => http.get("/advanced/quality/supplier", { params: supplierId ? { supplier_id: supplierId } : undefined });
export const saveSupplierQuality = (payload: unknown) => http.post("/advanced/quality/supplier", payload);
export const listSupplierQualitySources = (qualityId: string) => http.get(`/advanced/quality/supplier/${qualityId}/sources`);
export const approveSupplierQuality = (qualityId: string, comment = "") => http.post(`/advanced/quality/supplier/${qualityId}/approve`, { comment });
export const rejectSupplierQuality = (qualityId: string, comment: string) => http.post(`/advanced/quality/supplier/${qualityId}/reject`, { comment });
export const listQualityCosts = (period?: string) => http.get("/advanced/quality/cost", { params: period ? { period } : undefined });
export const createQualityCost = (payload: unknown) => http.post("/advanced/quality/cost", payload);
export const confirmQualityCost = (id: string, payload: unknown = {}) => http.post(`/advanced/quality/cost/${id}/confirm`, payload);
export const listCustomerClaims = (status?: string) => http.get("/advanced/quality/claims", { params: status ? { status } : undefined });
export const listCustomerClaimSources = (sourceType?: string, customerId?: string) => http.get("/advanced/quality/claims/sources", { params: { source_type: sourceType || undefined, customer_id: customerId || undefined } });
export const createCustomerClaim = (payload: unknown) => http.post("/advanced/quality/claims", payload);
export const updateCustomerClaim = (id: string, payload: unknown) => http.put(`/advanced/quality/claims/${id}`, payload);
export const transitionCustomerClaim = (id: string, payload: unknown) => http.put(`/advanced/quality/claims/${id}`, payload);

export const listShipments = (status?: string) => http.get("/advanced/transport/shipments", { params: status ? { status } : undefined });
export const createShipment = (payload: unknown) => http.post("/advanced/transport/shipments", payload);
export const transitionShipment = (id: string, payload: unknown) => http.post(`/advanced/transport/shipments/${id}/transition`, payload);
export const listOcrDocuments = () => http.get("/advanced/ocr/documents");
export const processOcrDocument = (payload: unknown) => http.post("/advanced/ocr/documents/process", payload);
