import { http } from "./http";
export const listBoms = () => http.get("/production/boms");
export const createBom = (payload: unknown) => http.post("/production/boms", payload);
export const submitBom = (id: string) => http.post(`/production/boms/${id}/submit`);
export const approveBom = (id: string) => http.post(`/production/boms/${id}/approve`);
export const disableBom = (id: string) => http.post(`/production/boms/${id}/disable`);
export const listMps = () => http.get("/production/mps");
export const createMps = (payload: unknown) => http.post("/production/mps", payload);
export const runMrp = (id: string) => http.post(`/production/mps/${id}/run-mrp`);
export const listWorkOrders = () => http.get("/production/work-orders");
export const createWorkOrder = (payload: unknown) => http.post("/production/work-orders", payload);
export const releaseWorkOrder = (id: string) => http.post(`/production/work-orders/${id}/release`);
export const issueMaterial = (id: string, items: unknown) => http.post(`/production/work-orders/${id}/issue`, { items });
export const reportWork = (id: string, payload: unknown) => http.post(`/production/work-orders/${id}/reports`, payload);
export const completeWorkOrder = (id: string) => http.post(`/production/work-orders/${id}/complete`);
export const cancelWorkOrder = (id: string) => http.post(`/production/work-orders/${id}/cancel`);
export const getWorkOrderReadiness = (id: string) => http.get(`/production/work-orders/${id}/readiness`);
export const getWorkOrderCost = (id: string) => http.get(`/production/work-orders/${id}/cost`);
export const listWorkOrderSchedules = (workOrderId?: string) => http.get("/production/schedules", { params: workOrderId ? { work_order_id: workOrderId } : undefined });
export const createWorkOrderSchedule = (id: string, payload: unknown) => http.post(`/production/work-orders/${id}/schedules`, payload);
export const listAlternateMaterials = (id: string) => http.get(`/production/work-orders/${id}/alternates`);
export const createAlternateMaterial = (id: string, payload: unknown) => http.post(`/production/work-orders/${id}/alternates`, payload);
export const listWorkOrderExceptions = (id: string) => http.get(`/production/work-orders/${id}/exceptions`);
export const createWorkOrderException = (id: string, payload: unknown) => http.post(`/production/work-orders/${id}/exceptions`, payload);
export const resolveWorkOrderException = (id: string, payload: unknown) => http.post(`/production/exceptions/${id}/resolve`, payload);
export const listWorkCenters = () => http.get("/production/work-centers");
export const createWorkCenter = (payload: unknown) => http.post("/production/work-centers", payload);
export const updateWorkCenter = (id: string, payload: unknown) => http.put(`/production/work-centers/${id}`, payload);
export const listCapacityCalendar = (params?: { date_from?: string; date_to?: string }) => http.get("/production/capacity-calendar", { params });
export const listCapacityLoad = (params?: { date_from?: string; date_to?: string }) => http.get("/production/capacity-load", { params });
export const upsertCapacityCalendar = (payload: unknown) => http.post("/production/capacity-calendar", payload);
export const listRoutings = () => http.get("/production/routings");
export const createRouting = (payload: unknown) => http.post("/production/routings", payload);
export const submitRouting = (id: string) => http.post(`/production/routings/${id}/submit`);
export const approveRouting = (id: string) => http.post(`/production/routings/${id}/approve`);
export const disableRouting = (id: string) => http.post(`/production/routings/${id}/disable`);
