<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { approveBudget, createBudget, createCashForecast, createReconciliationStatement, getAgingReport, listBudgets, listCashForecasts, listFinanceAccounts, listReconciliationStatements } from "../../api/finance";

type Row = Record<string, any>;
const loading = ref(false); const saving = ref(false);
const agingAr = ref<Record<string, any>>({}); const agingAp = ref<Record<string, any>>({}); const budgets = ref<Row[]>([]); const forecasts = ref<Row[]>([]); const statements = ref<Row[]>([]); const accounts = ref<Row[]>([]);
const budgetForm = reactive({ budget_period: new Date().toISOString().slice(0, 7), account_code: "", department_id: "", budget_amount: 0, note: "" });
const forecastForm = reactive({ forecast_date: new Date().toISOString().slice(0, 10), inflow_amount: 0, outflow_amount: 0, source: "manual", note: "" });
const statementForm = reactive({ statement_type: "ar", party_id: "", period: new Date().toISOString().slice(0, 7), statement_amount: 0, note: "" });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "财务控制接口失败"); return response.data.data; }
async function load() { loading.value = true; try { const [ar, ap, budget, forecast, statement, account] = await Promise.all([getAgingReport("ar"), getAgingReport("ap"), listBudgets(), listCashForecasts(), listReconciliationStatements(), listFinanceAccounts({ page: 1, page_size: 200 })]); agingAr.value = unwrap(ar)?.summary || {}; agingAp.value = unwrap(ap)?.summary || {}; budgets.value = unwrap(budget)?.items || []; forecasts.value = unwrap(forecast)?.items || []; statements.value = unwrap(statement)?.items || []; accounts.value = unwrap(account)?.items || []; if (!budgetForm.account_code && accounts.value.length) budgetForm.account_code = String(accounts.value[0].code); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "财务控制数据加载失败"); } finally { loading.value = false; } }
async function saveBudget() { if (!budgetForm.account_code || budgetForm.budget_amount < 0) { ElMessage.warning("请选择科目并填写预算金额"); return; } saving.value = true; try { unwrap(await createBudget(budgetForm)); ElMessage.success("预算已保存"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "预算保存失败"); } finally { saving.value = false; } }
async function approve(row: Row) { try { unwrap(await approveBudget(String(row.id))); ElMessage.success("预算已审批"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "预算审批失败"); } }
async function saveForecast() { if (forecastForm.inflow_amount < 0 || forecastForm.outflow_amount < 0) { ElMessage.warning("现金流金额不能为负数"); return; } saving.value = true; try { unwrap(await createCashForecast(forecastForm)); ElMessage.success("现金预测已保存"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "现金预测保存失败"); } finally { saving.value = false; } }
async function saveStatement() { if (!statementForm.party_id.trim() || statementForm.statement_amount < 0) { ElMessage.warning("请填写往来方和对账金额"); return; } saving.value = true; try { unwrap(await createReconciliationStatement(statementForm)); ElMessage.success("对账单已生成"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "对账单生成失败"); } finally { saving.value = false; } }
onMounted(load);
</script>

<template>
  <section class="page-stack"><header class="page-heading"><div><small>FINANCE CONTROL</small><h1>财务控制中心</h1><p>集中查看应收应付账龄、预算执行、现金预测和往来对账差异。</p></div><el-button :loading="loading" @click="load">刷新</el-button></header>
    <el-card shadow="never"><template #header>应收 / 应付账龄</template><div class="aging-grid"><div><h3>应收账款</h3><div class="metrics"><span v-for="(value,key) in agingAr" :key="`ar-${key}`"><small>{{ key }}</small><strong>{{ value }}</strong></span></div></div><div><h3>应付账款</h3><div class="metrics"><span v-for="(value,key) in agingAp" :key="`ap-${key}`"><small>{{ key }}</small><strong>{{ value }}</strong></span></div></div></div></el-card>
    <el-card shadow="never"><template #header>预算执行</template><div class="form-grid"><el-date-picker v-model="budgetForm.budget_period" type="month" value-format="YYYY-MM" placeholder="预算期间" /><el-select v-model="budgetForm.account_code" placeholder="预算科目" filterable><el-option v-for="item in accounts" :key="String(item.id)" :label="`${item.code} · ${item.name}`" :value="String(item.code)" /></el-select><el-input-number v-model="budgetForm.budget_amount" :min="0" :precision="2" /><el-input v-model="budgetForm.department_id" placeholder="部门 ID（可选）" /><el-button type="primary" :loading="saving" @click="saveBudget">保存预算</el-button></div><el-table :data="budgets" stripe><el-table-column prop="budget_period" label="期间" /><el-table-column prop="account_code" label="科目" /><el-table-column prop="budget_amount" label="预算" /><el-table-column prop="actual_amount" label="实际" /><el-table-column prop="variance_amount" label="差异" /><el-table-column prop="status" label="状态" /><el-table-column label="操作" width="90"><template #default="scope"><el-button v-if="scope.row.status === 'draft'" link type="primary" @click="approve(scope.row)">审批</el-button></template></el-table-column></el-table></el-card>
    <el-card shadow="never"><template #header>现金预测</template><div class="form-grid"><el-date-picker v-model="forecastForm.forecast_date" type="date" value-format="YYYY-MM-DD" placeholder="预测日期" /><el-input-number v-model="forecastForm.inflow_amount" :min="0" :precision="2" /><el-input-number v-model="forecastForm.outflow_amount" :min="0" :precision="2" /><el-input v-model="forecastForm.source" placeholder="来源" /><el-button type="primary" :loading="saving" @click="saveForecast">保存预测</el-button></div><el-table :data="forecasts" stripe><el-table-column prop="forecast_date" label="日期" /><el-table-column prop="inflow_amount" label="流入" /><el-table-column prop="outflow_amount" label="流出" /><el-table-column prop="net_amount" label="净额" /><el-table-column prop="source" label="来源" /></el-table></el-card>
    <el-card shadow="never"><template #header>往来对账</template><div class="form-grid"><el-select v-model="statementForm.statement_type" style="width:110px"><el-option label="应收" value="ar" /><el-option label="应付" value="ap" /></el-select><el-input v-model="statementForm.party_id" placeholder="客户/供应商 ID" /><el-date-picker v-model="statementForm.period" type="month" value-format="YYYY-MM" placeholder="对账期间" /><el-input-number v-model="statementForm.statement_amount" :min="0" :precision="2" /><el-button type="primary" :loading="saving" @click="saveStatement">生成对账单</el-button></div><el-table :data="statements" stripe><el-table-column prop="statement_no" label="对账单号" /><el-table-column prop="statement_type" label="类型" /><el-table-column prop="party_id" label="往来方" /><el-table-column prop="statement_amount" label="对账金额" /><el-table-column prop="reconciled_amount" label="系统金额" /><el-table-column prop="difference_amount" label="差异" /><el-table-column prop="status" label="状态" /></el-table></el-card>
  </section>
</template>

<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.aging-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.metrics{display:flex;gap:18px;flex-wrap:wrap}.metrics span{display:flex;flex-direction:column;gap:6px;min-width:90px}.metrics small{color:var(--erp-muted-text)}.form-grid{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.form-grid>*{min-width:150px}@media(max-width:900px){.aging-grid{grid-template-columns:1fr}}</style>
