<script setup lang="ts">
import { ref } from "vue";
import { ElMessage } from "element-plus";
import { getCustomer360 } from "../../api/phase2";
import { useMasterOptions } from "../../composables/useMasterOptions";
import StatusTag from "../../components/StatusTag.vue";
import { stageLabels } from "../../utils/labels";
type Row = Record<string, any>;
const { customers, loadOptions } = useMasterOptions(); const customerId = ref(""); const data = ref<Row | null>(null); const loading = ref(false);
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
async function load() { if (!customerId.value) return ElMessage.warning("请选择客户"); loading.value = true; try { data.value = unwrap(await getCustomer360(customerId.value)); } catch (error) { data.value = null; ElMessage.error(error instanceof Error ? error.message : "客户 360 加载失败"); } finally { loading.value = false; } }
function stageLabel(value: unknown) { return stageLabels[String(value || "")] || String(value || "-"); }
loadOptions(["customers"]);
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>CRM / CUSTOMER 360</small><h1>客户 360</h1><p>聚合联系人、线索、商机、跟进、报价/订单、回款、合同和服务。</p></div><el-space><el-select v-model="customerId" filterable clearable placeholder="选择客户" style="width:260px"><el-option v-for="item in customers" :key="item.value" v-bind="item" /></el-select><el-button type="primary" :loading="loading" @click="load">加载客户档案</el-button></el-space></header><el-empty v-if="!data" description="请选择客户查看全景" /><template v-else><el-card shadow="never"><div class="customer-head"><div><small>{{ data.customer.code }}</small><h2>{{ data.customer.name }}</h2><span>{{ data.customer.contact_name || "暂无联系人" }} · {{ data.customer.contact_phone || "暂无电话" }}</span></div><div class="summary"><el-statistic title="联系人" :value="data.summary.contact_count" /><el-statistic title="商机" :value="data.summary.opportunity_count" /><el-statistic title="订单" :value="data.summary.order_count" /><el-statistic title="未结服务" :value="data.summary.open_case_count" /><el-statistic title="回款" :value="data.summary.receipt_amount || 0" /></div></div></el-card><el-tabs type="border-card">
    <el-tab-pane label="联系人"><el-table :data="data.contacts" stripe><el-table-column prop="name" label="姓名" /><el-table-column prop="title" label="职位" /><el-table-column prop="phone" label="电话" /><el-table-column prop="email" label="邮箱" /></el-table></el-tab-pane>
    <el-tab-pane label="线索与商机"><el-table :data="[...data.leads, ...data.opportunities]" stripe><el-table-column prop="lead_no" label="线索号" /><el-table-column prop="opportunity_no" label="商机号" /><el-table-column prop="name" label="名称" /><el-table-column label="状态"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column><el-table-column label="阶段"><template #default="scope"><el-tag v-if="scope.row.stage" effect="light">{{ stageLabel(scope.row.stage) }}</el-tag></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="跟进"><el-table :data="data.follow_ups" stripe><el-table-column prop="occurred_at" label="发生时间" /><el-table-column prop="content" label="跟进内容" min-width="300" /><el-table-column prop="due_date" label="下次计划" /><el-table-column label="状态"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="订单"><el-table :data="data.orders" stripe><el-table-column prop="doc_no" label="订单号" /><el-table-column prop="order_date" label="日期" /><el-table-column prop="expected_date" label="预计交期" /><el-table-column prop="total_amount" label="金额" /><el-table-column label="状态"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="回款"><el-table :data="data.receipts" stripe><el-table-column prop="doc_no" label="收款单号" /><el-table-column prop="receipt_date" label="日期" /><el-table-column prop="amount" label="金额" /><el-table-column label="状态"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="服务"><el-table :data="data.service_cases" stripe><el-table-column prop="case_no" label="服务单号" /><el-table-column prop="title" label="问题" /><el-table-column prop="priority" label="优先级" /><el-table-column label="状态"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column><el-table-column prop="due_date" label="期限" /></el-table></el-tab-pane>
  </el-tabs></template></section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:20px}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.customer-head{display:flex;justify-content:space-between;gap:20px;align-items:center}.customer-head h2{margin:5px 0}.customer-head span{color:var(--erp-muted-text)}.summary{display:flex;gap:24px}@media(max-width:900px){.page-heading,.customer-head{flex-direction:column;align-items:stretch}.summary{justify-content:space-between}}</style>
