<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { useClientPagination } from "../../composables/useClientPagination";
import { bulkConfirmPlannedOrders, comparePlanRuns, confirmPlannedOrder, createPlanRun, getPlanRun, ignorePlannedOrder, listPlanRuns, resolvePlanException } from "../../api/production";
import { useMasterOptions } from "../../composables/useMasterOptions";
import { statusLabel } from "../../utils/labels";

type Row = Record<string, any>;
const loading = ref(false); const running = ref(false); const saving = ref(false); const runs = ref<Row[]>([]); const selectedRun = ref<Row | null>(null); const drawerVisible = ref(false); const selectedIds = ref<string[]>([]); const compareVisible = ref(false); const compareBaseline = ref(""); const compareCandidate = ref(""); const compareResult = ref<Row | null>(null);
const { pagedRows: planRunRows, page: planRunPage, pageSize: planRunPageSize, total: planRunTotal, updatePageSize: updatePlanRunPageSize } = useClientPagination(runs);
const today = new Date().toISOString().slice(0, 10);
const form = reactive({ plan_from: today, plan_to: today, warehouse_id: "", demand_sources: ["sales_order", "mps", "forecast", "project", "subcontract", "manual"] });
const { warehouses, loadOptions } = useMasterOptions();
const orders = computed<Row[]>(() => selectedRun.value?.planned_orders || []);
const exceptions = computed<Row[]>(() => selectedRun.value?.exceptions || []);
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "计划控制塔接口失败"); return response.data.data; }
function money(value: any) { return Number(value || 0).toLocaleString("zh-CN", { maximumFractionDigits: 2 }); }
function sourceLabel(value: string) { return ({ sales_order: "销售订单", mps: "主生产计划", forecast: "预测需求", project: "项目需求", subcontract: "委外需求", manual: "手工需求" } as Record<string, string>)[value] || value; }
async function load() { loading.value = true; try { const result = unwrap(await listPlanRuns()); runs.value = (result?.items || []).map((item: Row) => ({ ...item, status: statusLabel(item.status) })); if (!selectedRun.value && runs.value.length) await openRun(runs.value[0]); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "计划运行加载失败"); } finally { loading.value = false; } }
async function openRun(row: Row) { try { selectedRun.value = unwrap(await getPlanRun(String(row.id))); drawerVisible.value = true; selectedIds.value = []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "计划运行详情加载失败"); } }
async function run() { if (!form.plan_from || !form.plan_to || form.plan_to < form.plan_from) return ElMessage.warning("请填写有效计划期间"); running.value = true; try { const data = unwrap(await createPlanRun({ ...form, warehouse_id: form.warehouse_id || undefined })); ElMessage.success(`计划运行完成：${data.run_no}`); await load(); await openRun(data); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "计划运行失败"); } finally { running.value = false; } }
async function confirmOne(row: Row) { saving.value = true; try { unwrap(await confirmPlannedOrder(String(row.id))); ElMessage.success("建议已转正式单据"); if (selectedRun.value) await openRun(selectedRun.value); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "建议转单失败"); } finally { saving.value = false; } }
async function confirmBatch() { if (!selectedIds.value.length) return ElMessage.warning("请先选择待确认建议"); saving.value = true; try { unwrap(await bulkConfirmPlannedOrders(selectedIds.value)); ElMessage.success("批量转单完成"); if (selectedRun.value) await openRun(selectedRun.value); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "批量转单失败"); } finally { saving.value = false; } }
async function ignore(row: Row) { try { unwrap(await ignorePlannedOrder(String(row.id))); ElMessage.success("建议已忽略"); if (selectedRun.value) await openRun(selectedRun.value); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "忽略建议失败"); } }
async function resolveException(row: Row) { try { const resolution = window.prompt("请输入处理说明", "已调整计划并复核"); if (!resolution) return; unwrap(await resolvePlanException(String(row.id), resolution)); ElMessage.success("计划异常已处理"); if (selectedRun.value) await openRun(selectedRun.value); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "处理计划异常失败"); } }
async function compare() { if (!compareBaseline.value || !compareCandidate.value || compareBaseline.value === compareCandidate.value) return ElMessage.warning("请选择两个不同的计划版本"); try { compareResult.value = unwrap(await comparePlanRuns(compareBaseline.value, compareCandidate.value)); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "计划版本对比失败"); } }
function toggle(row: Row, checked: boolean) { selectedIds.value = checked ? [...new Set([...selectedIds.value, String(row.id)])] : selectedIds.value.filter((id) => id !== String(row.id)); }
onMounted(async () => { await Promise.all([load(), loadOptions(["warehouses"])]); });
</script>

<template>
  <section class="page-stack">
    <header class="page-heading"><div><small>PLANNING CONTROL TOWER</small><h1>供需计划控制塔</h1><p>从需求来源到建议采购/工单，保留可解释的输入快照、异常和人工动作。</p></div><el-button :loading="loading" @click="load">刷新</el-button></header>
    <el-card shadow="never"><div class="run-form"><el-date-picker v-model="form.plan_from" type="date" value-format="YYYY-MM-DD" placeholder="计划开始" /><el-date-picker v-model="form.plan_to" type="date" value-format="YYYY-MM-DD" placeholder="计划结束" /><el-select v-model="form.warehouse_id" clearable filterable placeholder="组织/工厂仓库" style="width:220px"><el-option v-for="item in warehouses" :key="item.value" v-bind="item" /></el-select><el-checkbox-group v-model="form.demand_sources"><el-checkbox v-for="source in ['sales_order','mps','manual']" :key="source" :value="source">{{ sourceLabel(source) }}</el-checkbox></el-checkbox-group><el-button type="primary" :loading="running" @click="run">运行计划</el-button></div></el-card>
    <div class="kpi-grid" v-if="selectedRun"><el-card shadow="never"><small>净需求</small><strong>{{ money(selectedRun.output_snapshot?.net_requirement) }}</strong><span>运行 {{ selectedRun.run_no }}</span></el-card><el-card shadow="never"><small>缺料物料</small><strong>{{ selectedRun.output_snapshot?.material_count || 0 }}</strong><span>按物料聚合</span></el-card><el-card shadow="never"><small>产能过载</small><strong>{{ exceptions.filter((item) => item.exception_type === 'capacity_overload').length }}</strong><span>需调整日期/工作中心</span></el-card><el-card shadow="never"><small>建议采购/工单</small><strong>{{ selectedRun.output_snapshot?.planned_order_count || 0 }}</strong><span>可批量确认</span></el-card></div>
    <el-card shadow="never"><template #header><div class="card-heading"><span>计划运行版本</span><el-button type="primary" plain :disabled="runs.length < 2" @click="compareVisible = true">版本对比</el-button></div></template><el-table v-loading="loading" :data="planRunRows" stripe @row-click="openRun"><el-table-column prop="run_no" label="运行批次" min-width="220" /><el-table-column prop="plan_from" label="开始" width="120" /><el-table-column prop="plan_to" label="结束" width="120" /><el-table-column prop="algorithm_version" label="算法版本" width="180" /><el-table-column prop="planned_order_count" label="建议数" width="90" /><el-table-column prop="exception_count" label="异常数" width="90" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="90"><template #default="scope"><el-button link type="primary" @click.stop="openRun(scope.row)">查看</el-button></template></el-table-column><template #empty><el-empty description="暂无计划运行，请先运行一个版本" /></template></el-table><ClientPagination v-model:page="planRunPage" v-model:page-size="planRunPageSize" :total="planRunTotal" @update:page-size="updatePlanRunPageSize" /></el-card>
    <el-drawer v-model="drawerVisible" title="计划运行依据与建议动作" size="76%"><template v-if="selectedRun"><div class="drawer-toolbar"><div><el-tag type="info">{{ selectedRun.run_no }}</el-tag><span class="muted">输入 {{ selectedRun.input_snapshot?.demand_count || 0 }} 条需求，算法 {{ selectedRun.algorithm_version }}</span></div><div><el-button :loading="saving" :disabled="!selectedIds.length" type="primary" @click="confirmBatch">批量转单</el-button></div></div><el-alert v-if="exceptions.length" title="存在需要角色处理的计划异常" type="warning" :closable="false" class="section-gap" /><el-table v-if="exceptions.length" :data="exceptions" stripe class="section-gap"><el-table-column prop="exception_type" label="异常" /><el-table-column prop="severity" label="严重度" /><el-table-column prop="material_id" label="物料" /><el-table-column prop="impact_quantity" label="影响数量" /><el-table-column prop="status" label="状态" /><el-table-column label="动作" width="100"><template #default="scope"><el-button v-if="scope.row.status !== 'resolved'" link type="success" @click="resolveException(scope.row)">处理</el-button></template></el-table-column></el-table><el-table :data="orders" stripe class="section-gap"><el-table-column label="选择" width="60"><template #default="scope"><el-checkbox v-if="scope.row.status === 'pending'" :model-value="selectedIds.includes(String(scope.row.id))" @change="(checked: boolean) => toggle(scope.row, checked)" /></template></el-table-column><el-table-column prop="order_type" label="建议类型" width="110" /><el-table-column prop="material_id" label="物料" min-width="150" /><el-table-column prop="warehouse_id" label="仓库" min-width="150" /><el-table-column prop="due_date" label="交期" width="120" /><el-table-column prop="quantity" label="建议数量" width="120" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="动作" width="150"><template #default="scope"><el-button v-if="scope.row.status === 'pending'" link type="primary" :loading="saving" @click="confirmOne(scope.row)">转正式单</el-button><el-button v-if="scope.row.status === 'pending'" link type="warning" @click="ignore(scope.row)">忽略</el-button></template></el-table-column><template #empty><el-empty description="当前版本没有建议单" /></template></el-table><el-divider>输入快照</el-divider><pre class="snapshot">{{ JSON.stringify(selectedRun.input_snapshot, null, 2) }}</pre></template></el-drawer>
    <el-dialog v-model="compareVisible" title="计划版本对比" width="860px"><div class="compare-form"><el-select v-model="compareBaseline" placeholder="基准版本"><el-option v-for="item in runs" :key="`base-${item.id}`" :label="item.run_no" :value="String(item.id)" /></el-select><el-select v-model="compareCandidate" placeholder="候选版本"><el-option v-for="item in runs" :key="`candidate-${item.id}`" :label="item.run_no" :value="String(item.id)" /></el-select><el-button type="primary" @click="compare">生成差异</el-button></div><el-alert v-if="compareResult" :title="`变更 ${compareResult.summary?.changed_lines || 0} 行，增加 ${compareResult.summary?.increase || 0}，减少 ${compareResult.summary?.decrease || 0}`" type="info" :closable="false" class="section-gap" /><el-table v-if="compareResult" :data="compareResult.rows" stripe class="section-gap"><el-table-column prop="material_id" label="物料" /><el-table-column prop="due_date" label="交期" /><el-table-column prop="before_quantity" label="基准数量" /><el-table-column prop="after_quantity" label="候选数量" /><el-table-column prop="delta_quantity" label="差异" /><el-table-column prop="after_order_type" label="候选建议" /></el-table></el-dialog>
  </section>
</template>

<style scoped>
.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p,.muted{margin:0;color:var(--erp-muted-text)}.card-heading{display:flex;justify-content:space-between;align-items:center}.run-form{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.run-form :deep(.el-checkbox){margin-right:12px}.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.kpi-grid .el-card{display:flex;flex-direction:column;gap:7px}.kpi-grid small,.kpi-grid span{color:var(--erp-muted-text)}.kpi-grid strong{font-size:25px;color:var(--erp-brand)}.drawer-toolbar{display:flex;justify-content:space-between;align-items:center}.drawer-toolbar>div:first-child{display:flex;align-items:center;gap:10px}.compare-form{display:flex;gap:12px;align-items:center}.compare-form .el-select{flex:1}.section-gap{margin-top:16px}.snapshot{max-height:260px;overflow:auto;background:var(--erp-surface-soft);padding:12px;border-radius:8px;font-size:12px}@media(max-width:900px){.kpi-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.kpi-grid{grid-template-columns:1fr}.compare-form{flex-direction:column;align-items:stretch}}
</style>
