<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import {
  approveRouting, createRouting, createWorkCenter, disableRouting, listBoms, listCapacityCalendar, listCapacityLoad,
  listRoutings, listWorkCenters, submitRouting, updateWorkCenter, upsertCapacityCalendar,
} from "../../api/production";
import { useMasterOptions } from "../../composables/useMasterOptions";
import { useClientPagination } from "../../composables/useClientPagination";
import { localDateString } from "../../utils/time";

type Row = Record<string, any>;
const activeTab = ref("routing"); const loading = ref(false); const saving = ref(false); const actionLoading = ref<string | null>(null);
const centers = ref<Row[]>([]); const calendars = ref<Row[]>([]); const loads = ref<Row[]>([]); const routings = ref<Row[]>([]); const boms = ref<Row[]>([]);
const centerVisible = ref(false); const routingVisible = ref(false); const capacityVisible = ref(false); const editingCenter = ref<Row | null>(null);
const centerForm = reactive({ code: "", name: "", daily_capacity_hours: 8, efficiency_rate: 1, labor_rate: 0, overhead_rate: 0, status: "active" });
const capacityForm = reactive({ work_center_id: "", capacity_date: localDateString(), available_hours: 8, note: "" });
const routingForm = reactive({ material_id: "", bom_id: "", routing_version: "1.0", effective_from: localDateString(), effective_to: "", operations: [{ work_center_id: "", operation_name: "", setup_hours: 0, run_hours_per_unit: 0 }] });
const { materials, loadOptions } = useMasterOptions();
const { pagedRows: routingRows, page: routingPage, pageSize: routingPageSize, total: routingTotal, updatePageSize: updateRoutingPageSize } = useClientPagination(routings);
const { pagedRows: centerRows, page: centerPage, pageSize: centerPageSize, total: centerTotal, updatePageSize: updateCenterPageSize } = useClientPagination(centers);
const { pagedRows: calendarRows, page: calendarPage, pageSize: calendarPageSize, total: calendarTotal, updatePageSize: updateCalendarPageSize } = useClientPagination(calendars);
const { pagedRows: loadRows, page: loadPage, pageSize: loadPageSize, total: loadTotal, updatePageSize: updateLoadPageSize } = useClientPagination(loads);
const statusLabels: Record<string, string> = { draft: "草稿", submitted: "已提交", approved: "已审核", disabled: "已停用", active: "启用", inactive: "停用" };
function dataList(response: any, fallback: string) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || fallback); return Array.isArray(response.data.data) ? response.data.data : []; }
function materialLabel(id: unknown) { const value = String(id || ""); return materials.value.find((item) => item.value === value)?.label || value || "-"; }
function centerLabel(id: unknown) { const row = centers.value.find((item) => item.id === id); return row ? `${row.code} · ${row.name}` : String(id || "-"); }
function bomOptions() { return boms.value.filter((item) => item.status === "approved" && (!routingForm.material_id || item.material_id === routingForm.material_id)); }
async function load() { loading.value = true; try { const [centerResponse, capacityResponse, loadResponse, routingResponse, bomResponse] = await Promise.all([listWorkCenters(), listCapacityCalendar(), listCapacityLoad(), listRoutings(), listBoms()]); centers.value = dataList(centerResponse, "工作中心加载失败"); calendars.value = dataList(capacityResponse, "产能日历加载失败"); loads.value = dataList(loadResponse, "产能负荷加载失败"); routings.value = dataList(routingResponse, "工艺路线加载失败"); boms.value = dataList(bomResponse, "BOM 加载失败"); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "生产资源加载失败"); } finally { loading.value = false; } }
function openCenter(row?: Row) { editingCenter.value = row || null; centerForm.code = row?.code || ""; centerForm.name = row?.name || ""; centerForm.daily_capacity_hours = Number(row?.daily_capacity_hours || 8); centerForm.efficiency_rate = Number(row?.efficiency_rate || 1); centerForm.labor_rate = Number(row?.labor_rate || 0); centerForm.overhead_rate = Number(row?.overhead_rate || 0); centerForm.status = row?.status || "active"; centerVisible.value = true; }
async function saveCenter() { if (!centerForm.code.trim() || !centerForm.name.trim()) return ElMessage.warning("请填写工作中心编码和名称"); saving.value = true; try { const response = editingCenter.value ? await updateWorkCenter(editingCenter.value.id, centerForm) : await createWorkCenter(centerForm); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success(editingCenter.value ? "工作中心已更新" : "工作中心已创建"); centerVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "工作中心保存失败"); } finally { saving.value = false; } }
function openCapacity(row?: Row) { capacityForm.work_center_id = row?.work_center_id || centers.value.find((item) => item.status === "active")?.id || ""; capacityForm.capacity_date = row?.capacity_date || localDateString(); capacityForm.available_hours = Number(row?.available_hours || 8); capacityForm.note = row?.note || ""; capacityVisible.value = true; }
async function saveCapacity() { if (!capacityForm.work_center_id || !capacityForm.capacity_date) return ElMessage.warning("请选择工作中心和日期"); saving.value = true; try { const response = await upsertCapacityCalendar(capacityForm); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success("产能日历已保存"); capacityVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "产能保存失败"); } finally { saving.value = false; } }
function openRouting() { routingForm.material_id = ""; routingForm.bom_id = ""; routingForm.routing_version = "1.0"; routingForm.effective_from = localDateString(); routingForm.effective_to = ""; routingForm.operations = [{ work_center_id: "", operation_name: "", setup_hours: 0, run_hours_per_unit: 0 }]; routingVisible.value = true; }
function addOperation() { routingForm.operations.push({ work_center_id: "", operation_name: "", setup_hours: 0, run_hours_per_unit: 0 }); }
function removeOperation(index: number) { if (routingForm.operations.length > 1) routingForm.operations.splice(index, 1); }
async function saveRouting() { if (!routingForm.material_id || !routingForm.bom_id || routingForm.operations.some((item) => !item.work_center_id || !item.operation_name.trim())) return ElMessage.warning("请选择成品、BOM，并补全每道工序"); saving.value = true; try { const response = await createRouting({ ...routingForm, effective_to: routingForm.effective_to || null }); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success("工艺路线已创建"); routingVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "工艺路线保存失败"); } finally { saving.value = false; } }
async function routingAction(row: Row, kind: "submit" | "approve" | "disable") { const labels = { submit: "提交", approve: "审核", disable: "停用" }; try { await ElMessageBox.confirm(`确认${labels[kind]}工艺路线 ${row.routing_version}？`, "操作确认", { type: "warning" }); actionLoading.value = row.id; const response = kind === "submit" ? await submitRouting(row.id) : kind === "approve" ? await approveRouting(row.id) : await disableRouting(row.id); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success(`${labels[kind]}成功`); await load(); } catch (error: any) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "操作失败"); } finally { actionLoading.value = null; } }
onMounted(async () => { await Promise.all([loadOptions(["materials"]), load()]); });
</script>

<template>
  <section class="page-stack"><el-page-header content="工艺与产能" /><el-alert title="工艺路线关联已审核 BOM；产能日历按日期覆盖工作中心默认有效产能。" type="info" show-icon />
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="工艺路线" name="routing"><el-space><el-button type="primary" :disabled="!centers.some((item) => item.status === 'active')" @click="openRouting">新建工艺路线</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space><el-table v-loading="loading" :data="routingRows" stripe><el-table-column prop="routing_version" label="版本" width="100" /><el-table-column label="成品物料" min-width="180"><template #default="scope">{{ materialLabel(scope.row.material_id) }}</template></el-table-column><el-table-column prop="effective_from" label="生效日期" width="130" /><el-table-column label="工序" min-width="260"><template #default="scope"><el-space wrap><el-tag v-for="item in scope.row.operations" :key="item.id" effect="plain">{{ item.line_no }}. {{ item.operation_name }}</el-tag></el-space></template></el-table-column><el-table-column label="状态" width="100"><template #default="scope">{{ statusLabels[scope.row.status] || scope.row.status }}</template></el-table-column><el-table-column label="操作" width="180"><template #default="scope"><el-button v-if="scope.row.status === 'draft'" link type="primary" :loading="actionLoading === scope.row.id" @click="routingAction(scope.row, 'submit')">提交</el-button><el-button v-if="scope.row.status === 'submitted'" link type="success" :loading="actionLoading === scope.row.id" @click="routingAction(scope.row, 'approve')">审核</el-button><el-button v-if="scope.row.status === 'approved'" link type="warning" :loading="actionLoading === scope.row.id" @click="routingAction(scope.row, 'disable')">停用</el-button></template></el-table-column></el-table><ClientPagination v-model:page="routingPage" v-model:page-size="routingPageSize" :total="routingTotal" @update:page-size="updateRoutingPageSize" /></el-tab-pane>
      <el-tab-pane label="工作中心" name="center"><el-space><el-button type="primary" @click="openCenter()">新建工作中心</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space><el-table v-loading="loading" :data="centerRows" stripe><el-table-column prop="code" label="编码" width="130" /><el-table-column prop="name" label="名称" min-width="180" /><el-table-column prop="daily_capacity_hours" label="标准工时/天" width="140" /><el-table-column prop="efficiency_rate" label="效率系数" width="120" /><el-table-column prop="labor_rate" label="人工费率/时" width="130" /><el-table-column prop="overhead_rate" label="制造费率/时" width="130" /><el-table-column label="状态" width="100"><template #default="scope">{{ statusLabels[scope.row.status] || scope.row.status }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="primary" @click="openCenter(scope.row)">编辑</el-button></template></el-table-column></el-table><ClientPagination v-model:page="centerPage" v-model:page-size="centerPageSize" :total="centerTotal" @update:page-size="updateCenterPageSize" /></el-tab-pane>
      <el-tab-pane label="产能日历" name="capacity"><el-space><el-button type="primary" :disabled="!centers.length" @click="openCapacity()">维护产能</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space><el-table v-loading="loading" :data="calendarRows" stripe><el-table-column label="工作中心" min-width="180"><template #default="scope">{{ centerLabel(scope.row.work_center_id) }}</template></el-table-column><el-table-column prop="capacity_date" label="日期" width="140" /><el-table-column prop="available_hours" label="可用工时" width="140" /><el-table-column prop="note" label="说明" min-width="180" /><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="primary" @click="openCapacity(scope.row)">编辑</el-button></template></el-table-column></el-table><ClientPagination v-model:page="calendarPage" v-model:page-size="calendarPageSize" :total="calendarTotal" @update:page-size="updateCalendarPageSize" /></el-tab-pane>
      <el-tab-pane label="负荷看板" name="load"><el-alert title="按工单计划日期和工艺路线工时计算；红色表示计划负荷超过可用产能。" type="info" show-icon /><el-table v-loading="loading" :data="loadRows" stripe><el-table-column label="工作中心" min-width="180"><template #default="scope">{{ scope.row.code }} · {{ scope.row.name }}</template></el-table-column><el-table-column prop="capacity_date" label="日期" width="120" /><el-table-column prop="available_hours" label="可用工时" width="120" /><el-table-column prop="scheduled_hours" label="计划工时" width="120" /><el-table-column prop="remaining_hours" label="剩余工时" width="120" /><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="scope.row.overloaded ? 'danger' : 'success'">{{ scope.row.overloaded ? '超负荷' : '正常' }}</el-tag></template></el-table-column></el-table><ClientPagination v-model:page="loadPage" v-model:page-size="loadPageSize" :total="loadTotal" @update:page-size="updateLoadPageSize" /></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="centerVisible" :title="editingCenter ? '编辑工作中心' : '新建工作中心'" width="520px"><el-form label-width="110px"><el-form-item label="中心编码" required><el-input v-model="centerForm.code" :disabled="Boolean(editingCenter)" /></el-form-item><el-form-item label="中心名称" required><el-input v-model="centerForm.name" /></el-form-item><el-form-item label="标准工时/天"><el-input-number v-model="centerForm.daily_capacity_hours" :min="0.000001" :precision="2" /></el-form-item><el-form-item label="效率系数"><el-input-number v-model="centerForm.efficiency_rate" :min="0.0001" :max="2" :precision="4" /></el-form-item><el-form-item label="人工费率/时"><el-input-number v-model="centerForm.labor_rate" :min="0" :precision="2" /></el-form-item><el-form-item label="制造费率/时"><el-input-number v-model="centerForm.overhead_rate" :min="0" :precision="2" /></el-form-item><el-form-item v-if="editingCenter" label="状态"><el-select v-model="centerForm.status"><el-option label="启用" value="active" /><el-option label="停用" value="inactive" /></el-select></el-form-item></el-form><template #footer><el-button @click="centerVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveCenter">保存</el-button></template></el-dialog>
    <el-dialog v-model="capacityVisible" title="维护产能日历" width="520px"><el-form label-width="110px"><el-form-item label="工作中心" required><el-select v-model="capacityForm.work_center_id" filterable style="width: 100%"><el-option v-for="item in centers.filter((row) => row.status === 'active')" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="日期" required><el-date-picker v-model="capacityForm.capacity_date" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="可用工时"><el-input-number v-model="capacityForm.available_hours" :min="0" :precision="2" /></el-form-item><el-form-item label="说明"><el-input v-model="capacityForm.note" /></el-form-item></el-form><template #footer><el-button @click="capacityVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveCapacity">保存</el-button></template></el-dialog>
    <el-dialog v-model="routingVisible" title="新建工艺路线" width="820px"><el-form label-width="100px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="成品物料" required><el-select v-model="routingForm.material_id" filterable style="width: 100%" @change="routingForm.bom_id = ''"><el-option v-for="item in materials" :key="item.value" v-bind="item" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="审核 BOM" required><el-select v-model="routingForm.bom_id" style="width: 100%"><el-option v-for="item in bomOptions()" :key="item.id" :label="`版本 ${item.bom_version}`" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="路线版本"><el-input v-model="routingForm.routing_version" /></el-form-item></el-col><el-col :span="8"><el-form-item label="生效日期"><el-date-picker v-model="routingForm.effective_from" type="date" value-format="YYYY-MM-DD" /></el-form-item></el-col><el-col :span="8"><el-form-item label="失效日期"><el-date-picker v-model="routingForm.effective_to" type="date" value-format="YYYY-MM-DD" /></el-form-item></el-col></el-row><el-divider content-position="left">工序明细</el-divider><div v-for="(item, index) in routingForm.operations" :key="index" class="operation-row"><span>{{ index + 1 }}</span><el-select v-model="item.work_center_id" placeholder="工作中心" filterable><el-option v-for="center in centers.filter((row) => row.status === 'active')" :key="center.id" :label="`${center.code} · ${center.name}`" :value="center.id" /></el-select><el-input v-model="item.operation_name" placeholder="工序名称" /><el-input-number v-model="item.setup_hours" :min="0" :precision="2" placeholder="准备工时" /><el-input-number v-model="item.run_hours_per_unit" :min="0" :precision="4" placeholder="单位工时" /><el-button link type="danger" :disabled="routingForm.operations.length === 1" @click="removeOperation(index)">删除</el-button></div><el-button plain @click="addOperation">添加工序</el-button></el-form><template #footer><el-button @click="routingVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRouting">保存</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.page-stack { display: flex; flex-direction: column; gap: 16px; }
.operation-row { display: grid; grid-template-columns: 28px 1.3fr 1.3fr 1fr 1fr 52px; align-items: center; gap: 8px; margin-bottom: 12px; }
</style>
