<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { createCustomerClaim, createQualityCost, createSpc, listCustomerClaims, listQualityCosts, listSpc, listSupplierQuality, saveSupplierQuality, updateCustomerClaim } from "../../api/advanced";
import { useMasterOptions } from "../../composables/useMasterOptions";
type Row = Record<string, any>;
const spc = ref<Row[]>([]); const supplierQuality = ref<Row[]>([]); const costs = ref<Row[]>([]); const claims = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const dialog = ref(""); const { customers, suppliers, loadOptions } = useMasterOptions();
const spcForm = reactive({ material_id: "", metric: "", sample_value: 0, lsl: null as number | null, usl: null as number | null, cpk: null as number | null }); const supplierForm = reactive({ supplier_id: "", period: new Date().toISOString().slice(0, 7), inspection_count: 0, defect_count: 0, score: 0, note: "" }); const costForm = reactive({ period: new Date().toISOString().slice(0, 7), cost_type: "internal_failure", amount: 0, source_id: "", note: "" }); const claimForm = reactive({ customer_id: "", source_type: "sales_delivery", source_id: "", title: "", amount: 0 });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "质量接口返回失败"); return response.data.data; }
async function load() { loading.value = true; try { [spc.value, supplierQuality.value, costs.value, claims.value] = await Promise.all([listSpc().then(unwrap), listSupplierQuality().then(unwrap), listQualityCosts().then(unwrap), listCustomerClaims().then(unwrap)]); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "质量分析加载失败"); } finally { loading.value = false; } }
async function saveAction(action: () => Promise<any>, message: string) { saving.value = true; try { unwrap(await action()); ElMessage.success(message); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } finally { saving.value = false; } }
function open(kind: string) { dialog.value = kind; if (kind === "supplier") Object.assign(supplierForm, { supplier_id: suppliers.value[0]?.value || "", period: new Date().toISOString().slice(0, 7), inspection_count: 0, defect_count: 0, score: 0, note: "" }); if (kind === "claim") Object.assign(claimForm, { customer_id: customers.value[0]?.value || "", source_type: "sales_delivery", source_id: "", title: "", amount: 0 }); }
async function saveSpcForm() { if (!spcForm.material_id || !spcForm.metric) return ElMessage.warning("请填写物料和检测指标"); await saveAction(() => createSpc(spcForm), "SPC 样本已保存"); }
async function saveSupplierForm() { if (!supplierForm.supplier_id) return ElMessage.warning("请选择供应商"); await saveAction(() => saveSupplierQuality(supplierForm), "供应商质量已保存"); }
async function saveCostForm() { if (costForm.amount < 0) return ElMessage.warning("质量成本不能为负数"); await saveAction(() => createQualityCost(costForm), "质量成本已保存"); }
async function saveClaimForm() { if (!claimForm.customer_id || !claimForm.title) return ElMessage.warning("请选择客户并填写索赔标题"); await saveAction(() => createCustomerClaim(claimForm), "客户质量索赔已创建"); }
async function closeClaim(row: Row) { try { unwrap(await updateCustomerClaim(row.id, { status: "closed", root_cause: row.root_cause || "", resolution: row.resolution || "已完成整改" })); ElMessage.success("索赔已关闭"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "索赔关闭失败"); } }
onMounted(() => Promise.all([load(), loadOptions(["customers", "suppliers"]) ]));
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>QUALITY / ANALYTICS</small><h1>质量分析与索赔中心</h1><p>把 SPC 样本、供应商质量、质量成本和客户索赔统一到检验与 CAPA 证据链。</p></div><el-button :loading="loading" @click="load">刷新</el-button></header>
    <el-tabs type="border-card">
      <el-tab-pane label="SPC 控制" name="spc"><div class="toolbar"><el-input v-model="spcForm.material_id" placeholder="物料 ID" /><el-input v-model="spcForm.metric" placeholder="检测指标" /><el-input-number v-model="spcForm.sample_value" placeholder="样本值" /><el-input-number v-model="spcForm.lsl" placeholder="LSL" /><el-input-number v-model="spcForm.usl" placeholder="USL" /><el-button type="primary" @click="saveSpcForm">记录样本</el-button></div><el-table :data="spc" stripe><el-table-column prop="material_id" label="物料" /><el-table-column prop="metric" label="指标" /><el-table-column prop="sample_value" label="样本值" /><el-table-column prop="lsl" label="LSL" /><el-table-column prop="usl" label="USL" /><el-table-column prop="cpk" label="Cpk" /><el-table-column prop="status" label="控制状态" /></el-table></el-tab-pane>
      <el-tab-pane label="供应商质量" name="supplier"><div class="toolbar"><el-button type="primary" @click="open('supplier')">录入供应商质量</el-button></div><el-table :data="supplierQuality" stripe><el-table-column prop="supplier_id" label="供应商" /><el-table-column prop="period" label="期间" /><el-table-column prop="inspection_count" label="检验数" /><el-table-column prop="defect_count" label="缺陷数" /><el-table-column prop="defect_rate" label="缺陷率" /><el-table-column prop="score" label="质量得分" /><el-table-column prop="status" label="状态" /></el-table></el-tab-pane>
      <el-tab-pane label="质量成本" name="cost"><div class="toolbar"><el-input v-model="costForm.period" placeholder="YYYY-MM" /><el-select v-model="costForm.cost_type"><el-option label="预防成本" value="prevention" /><el-option label="鉴定成本" value="appraisal" /><el-option label="内部失败" value="internal_failure" /><el-option label="外部失败" value="external_failure" /></el-select><el-input-number v-model="costForm.amount" :min="0" /><el-input v-model="costForm.source_id" placeholder="来源单据" /><el-button type="primary" @click="saveCostForm">记录成本</el-button></div><el-table :data="costs" stripe><el-table-column prop="period" label="期间" /><el-table-column prop="cost_type" label="成本类型" /><el-table-column prop="amount" label="金额" /><el-table-column prop="source_id" label="来源" /><el-table-column prop="note" label="备注" /></el-table></el-tab-pane>
      <el-tab-pane label="客户质量索赔" name="claims"><div class="toolbar"><el-button type="primary" @click="open('claim')">新建索赔</el-button></div><el-table :data="claims" stripe><el-table-column prop="claim_no" label="索赔单号" /><el-table-column prop="customer_id" label="客户" /><el-table-column prop="title" label="标题" /><el-table-column prop="amount" label="金额" /><el-table-column prop="status" label="状态" /><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status !== 'closed'" link type="success" @click="closeClaim(scope.row)">关闭索赔</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs>
    <el-dialog :model-value="dialog === 'supplier'" title="供应商质量记录" width="560px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="100px"><el-form-item label="供应商" required><el-select v-model="supplierForm.supplier_id"><el-option v-for="item in suppliers" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="期间"><el-input v-model="supplierForm.period" /></el-form-item><el-form-item label="检验数"><el-input-number v-model="supplierForm.inspection_count" :min="0" /></el-form-item><el-form-item label="缺陷数"><el-input-number v-model="supplierForm.defect_count" :min="0" /></el-form-item><el-form-item label="质量得分"><el-input-number v-model="supplierForm.score" :min="0" :max="100" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveSupplierForm">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'claim'" title="新建客户质量索赔" width="560px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="客户" required><el-select v-model="claimForm.customer_id"><el-option v-for="item in customers" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="来源单据"><el-input v-model="claimForm.source_id" /></el-form-item><el-form-item label="索赔标题" required><el-input v-model="claimForm.title" /></el-form-item><el-form-item label="金额"><el-input-number v-model="claimForm.amount" :min="0" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveClaimForm">创建</el-button></template></el-dialog>
  </section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.toolbar>*{max-width:220px}</style>
