export type PageHeaderInfo = {
  eyebrow: string;
  title: string;
  description?: string;
};

export const pageHeaders: Record<string, PageHeaderInfo> = {
  "/workflow/tasks": { eyebrow: "WORKFLOW / MY TASKS", title: "我的待办", description: "审批流中指派给我的待审批任务。通过或驳回将同步驱动单据状态。" },
  "/dashboard": { eyebrow: "OPERATIONS / DASHBOARD", title: "经营看板" },
  "/analytics/reports": { eyebrow: "ANALYTICS / REPORTING", title: "BI 报表中心", description: "统一指标口径，按当前组织生成经营与运营报表，并保留可追溯运行记录。" },
  "/platform/metrics": { eyebrow: "METRICS / AI", title: "指标与异常助手", description: "沉淀指标口径、证据解释并扫描和闭环业务异常。" },
  "/operations/advanced": { eyebrow: "OPERATIONS / ADVANCED", title: "运输与预测", description: "运输状态、单据识别、预算执行和现金预测统一保留操作记录。" },
  "/documents": { eyebrow: "OPERATIONS / DOCUMENTS", title: "业务单据中心", description: "统一查看状态、责任对象和最新业务进展" },
  "/master-data/materials": { eyebrow: "MASTER DATA / MATERIALS", title: "物料档案" },
  "/master-data/customers": { eyebrow: "MASTER DATA / CUSTOMERS", title: "客户档案" },
  "/master-data/suppliers": { eyebrow: "MASTER DATA / SUPPLIERS", title: "供应商档案" },
  "/master-data/warehouses": { eyebrow: "MASTER DATA / WAREHOUSES", title: "仓库档案" },
  "/master-data/units": { eyebrow: "MASTER DATA / UNITS", title: "计量单位" },
  "/master-data/tax-rates": { eyebrow: "MASTER DATA / TAX RATES", title: "税率档案" },
  "/sales/quotes": { eyebrow: "SALES / QUOTES", title: "销售报价单" },
  "/sales/orders": { eyebrow: "SALES / ORDERS", title: "销售订单", description: "统一查看状态、责任对象和最新业务进展" },
  "/sales/returns": { eyebrow: "SALES / RETURNS", title: "销售退货单" },
  "/purchase/requests": { eyebrow: "PURCHASE / REQUESTS", title: "采购申请" },
  "/purchase/orders": { eyebrow: "PURCHASE / ORDERS", title: "采购订单" },
  "/purchase/returns": { eyebrow: "PURCHASE / RETURNS", title: "采购退货单" },
  "/srm/collaboration": { eyebrow: "SRM / SUPPLIER COLLABORATION", title: "供应商协同工作台", description: "询报价、报价比价、承诺交期、交付差异与供应商质量评分共用一条可追溯链路。" },
  "/inventory/stock": { eyebrow: "INVENTORY / STOCK", title: "库存台账" },
  "/inventory/transactions": { eyebrow: "INVENTORY / TRANSACTIONS", title: "库存流水" },
  "/inventory/transfers": { eyebrow: "INVENTORY / TRANSFERS", title: "库存调拨" },
  "/inventory/counts": { eyebrow: "INVENTORY / COUNTS", title: "库存盘点" },
  "/inventory/scan": { eyebrow: "INVENTORY / MOBILE SCAN", title: "移动扫码入库" },
  "/inventory/locations": { eyebrow: "INVENTORY / LOCATIONS", title: "库位管理" },
  "/inventory/batches": { eyebrow: "INVENTORY / BATCHES", title: "批次管理" },
  "/inventory/control-center": { eyebrow: "INVENTORY / CONTROL CENTER", title: "库存控制中心" },
  "/inventory/wms-tasks": { eyebrow: "WMS / EXECUTION", title: "仓库作业中心", description: "统一管理收货、上架、拣货、复核和异常任务，并支持拣货波次。" },
  "/finance/receivables": { eyebrow: "FINANCE / RECEIVABLES", title: "应收账款" },
  "/finance/payables": { eyebrow: "FINANCE / PAYABLES", title: "应付账款" },
  "/finance/expenses": { eyebrow: "FINANCE / EXPENSES", title: "费用报销" },
  "/finance/vouchers": { eyebrow: "FINANCE / VOUCHERS", title: "会计凭证" },
  "/finance/foundation": { eyebrow: "FINANCE / GENERAL LEDGER", title: "总账基础", description: "统一维护科目、核算维度、期间、银行账户与固定资产。" },
  "/finance/currencies": { eyebrow: "FINANCE / MULTI-CURRENCY", title: "多币种与汇率", description: "维护组织币种档案、本位币和按日汇率，供财务换算使用。" },
  "/finance/controls": { eyebrow: "FINANCE / CONTROL CENTER", title: "财务控制中心", description: "集中查看应收应付账龄、预算执行、现金预测和往来对账差异。" },
  "/crm/leads": { eyebrow: "CRM / LEADS", title: "CRM 线索" },
  "/crm/opportunities": { eyebrow: "CRM / OPPORTUNITIES", title: "CRM 商机" },
  "/crm/customer-360": { eyebrow: "CRM / CUSTOMER 360", title: "客户 360", description: "聚合联系人、线索、商机、跟进、报价/订单、回款、合同和服务。" },
  "/production/boms": { eyebrow: "PRODUCTION / BOM", title: "BOM 管理" },
  "/production/mrp": { eyebrow: "PRODUCTION / MRP", title: "MRP 运算" },
  "/production/planning": { eyebrow: "PRODUCTION / PLANNING", title: "供需计划控制塔", description: "从需求来源到建议采购/工单，保留可解释的输入快照、异常和人工动作。" },
  "/production/work-orders": { eyebrow: "PRODUCTION / WORK ORDERS", title: "生产工单" },
  "/production/resources": { eyebrow: "PRODUCTION / RESOURCES", title: "工艺与产能" },
  "/production/execution": { eyebrow: "PRODUCTION / EXECUTION", title: "生产执行控制台", description: "统一管理工单排程、替代料和车间异常，支持现场执行闭环。" },
  "/production/subcontract": { eyebrow: "PRODUCTION / SUBCONTRACT", title: "委外管理", description: "委外订单 创建→下达→发料→收货→生成应付与凭证 的完整闭环。" },
  "/plm/changes": { eyebrow: "PLM / ENGINEERING CHANGE", title: "PLM 工程变更中心", description: "维护产品版本、ECR/ECN、影响评估、审批和生效快照，防止错版生产。" },
  "/cost/allocations": { eyebrow: "COST / ALLOCATIONS", title: "成本分摊" },
  "/cost/period-close": { eyebrow: "COST / PERIOD CLOSE", title: "期间结账" },
  "/projects/cost": { eyebrow: "PROJECTS / COST CONTROL", title: "项目与成本控制中心", description: "以项目/WBS 为主线归集采购、工时、库存、收入和费用，显示预算、实际和利润风险。" },
  "/quality/inspections": { eyebrow: "QUALITY / INSPECTIONS", title: "质量检验" },
  "/quality/nonconformances": { eyebrow: "QUALITY / NONCONFORMANCES", title: "不合格与 CAPA" },
  "/quality/analytics": { eyebrow: "QUALITY / ANALYTICS", title: "质量分析与索赔中心", description: "把 SPC 样本、供应商质量、质量成本和客户索赔统一到检验与 CAPA 证据链。" },
  "/hr/employees": { eyebrow: "HR / EMPLOYEES", title: "人事员工档案" },
  "/hr/payroll": { eyebrow: "HR / PAYROLL", title: "薪资管理" },
  "/hr/people-ops": { eyebrow: "HR / PEOPLE OPERATIONS", title: "人事全生命周期中心", description: "覆盖招聘、入转调离、绩效、福利与薪资明细，员工状态变化保留可追溯记录。" },
  "/hr/leave": { eyebrow: "HR / LEAVE", title: "考勤与请假中心", description: "维护考勤登记、请假申请、审批状态与员工人事流程记录。" },
  "/eam/service": { eyebrow: "EAM / AFTER-SALES SERVICE", title: "资产与售后服务中心", description: "资产台账、保养维修、服务工单共用责任人、期限与状态闭环。" },
  "/system/operation-logs": { eyebrow: "SYSTEM / OPERATION LOGS", title: "操作日志" },
  "/system/users": { eyebrow: "SYSTEM / USERS", title: "用户管理" },
  "/system/admin": { eyebrow: "SYSTEM / PERMISSIONS", title: "权限设置" },
  "/system/backup": { eyebrow: "SYSTEM / BACKUP", title: "备份与恢复" },
  "/settings/parameters": { eyebrow: "SETTINGS / PARAMETERS", title: "全局参数" },
  "/settings/workflow": { eyebrow: "SETTINGS / WORKFLOW", title: "审批流配置" },
  "/settings/print-templates": { eyebrow: "SETTINGS / PRINT TEMPLATES", title: "打印模板" },
  "/settings/api-clients": { eyebrow: "SETTINGS / API CLIENTS", title: "OpenAPI 客户端" },
  "/settings/platform-events": { eyebrow: "SETTINGS / PLATFORM EVENTS", title: "事件订阅与投递", description: "为外部系统配置事件订阅，支持签名、投递结果、失败重试和死信处理。" },
  "/platform/group": { eyebrow: "PLATFORM / GROUP", title: "集团与内部交易", description: "管理组织成员、组织间交易与跨组织业务关系。" },
  "/platform/compliance": { eyebrow: "PLATFORM / COMPLIANCE", title: "税务与电子发票", description: "维护税码、发票池、业务原单关系和合规状态流转。" },
  "/platform/low-code": { eyebrow: "PLATFORM / LOW-CODE", title: "低代码对象", description: "配置对象字段与工作流，支持发布前校验和版本发布。" },
};
