<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { acceptRfq, compareRfqs, createRfq, createSupplierScore, listRfqs, listSupplierScores, quoteRfq } from "../../api/phase2";
import { useMasterOptions } from "../../composables/useMasterOptions";
import { useClientPagination } from "../../composables/useClientPagination";
import { statusLabel, tagTypeOf } from "../../utils/labels";
type Row = Record<string, any>;
const rows = ref<Row[]>([]); const compareRows = ref<Row[]>([]); const scores = ref<Row[]>([]); const loading = ref(false); const visible = ref(false); const quoteVisible = ref(false); const scoreVisible = ref(false); const selected = ref<Row | null>(null); const { suppliers, loadOptions } = useMasterOptions();
const form = reactive({ supplier_id: "", material_id: "", quantity: 1, due_date: "" }); const quoteForm = reactive({ quote_amount: 0, promised_date: "", supplier_note: "" }); const scoreForm = reactive({ supplier_id: "", period: new Date().toISOString().slice(0, 7), delivery_score: 0, quality_score: 0, service_score: 0, evidence: { source: "manual_review" } }); const compareMaterial = ref("");
const rfqFilters = reactive({ rfqNo: "", supplier: "", material: "", status: "" });
const filteredRfqRows = computed(() => rows.value.filter((row) => (!rfqFilters.rfqNo || String(row.rfq_no || "").toLowerCase().includes(rfqFilters.rfqNo.toLowerCase())) && (!rfqFilters.supplier || String(row.supplier_name || row.supplier_id || "").toLowerCase().includes(rfqFilters.supplier.toLowerCase())) && (!rfqFilters.material || String(row.material_name || row.material_id || "").toLowerCase().includes(rfqFilters.material.toLowerCase())) && (!rfqFilters.status || row.statusCode === rfqFilters.status)));
const { pagedRows: rfqRows, page: rfqPage, pageSize: rfqPageSize, total: rfqTotal, updatePageSize: updateRfqPageSize } = useClientPagination(filteredRfqRows);
const { pagedRows: comparePageRows, page: comparePage, pageSize: comparePageSize, total: compareTotal, updatePageSize: updateComparePageSize } = useClientPagination(compareRows);
const { pagedRows: scoreRows, page: scorePage, pageSize: scorePageSize, total: scoreTotal, updatePageSize: updateScorePageSize } = useClientPagination(scores);
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
async function load() { loading.value = true; try { const [rfqs, scoreData, compareData] = await Promise.all([listRfqs().then(unwrap), listSupplierScores().then(unwrap), compareRfqs(compareMaterial.value || undefined).then(unwrap)]); rows.value = (rfqs || []).map((row: Row) => ({ ...row, statusCode: row.status })); scores.value = scoreData || []; compareRows.value = compareData || []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "供应商协同加载失败"); } finally { loading.value = false; } }
async function loadCompare() { try { compareRows.value = unwrap(await compareRfqs(compareMaterial.value || undefined)) || []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "供应商比价加载失败"); } }
function supplierLabel(id: string) { return suppliers.value.find((item) => item.value === id)?.label || id; }
function openCreate() { Object.assign(form, { supplier_id: "", material_id: "", quantity: 1, due_date: "" }); visible.value = true; }
async function save() { if (!form.supplier_id || !form.material_id || form.quantity <= 0) return ElMessage.warning("请选择供应商、物料并填写有效数量"); try { unwrap(await createRfq({ ...form })); ElMessage.success("询价已创建"); visible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "询价创建失败"); } }
function openQuote(row: Row) { selected.value = row; Object.assign(quoteForm, { quote_amount: Number(row.quote_amount || 0), promised_date: row.promised_date || "", supplier_note: row.supplier_note || "" }); quoteVisible.value = true; }
async function saveQuote() { if (!selected.value || quoteForm.quote_amount <= 0) return ElMessage.warning("请填写有效报价"); try { unwrap(await quoteRfq(selected.value.id, { ...quoteForm })); ElMessage.success("供应商报价已保存"); quoteVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "报价保存失败"); } }
async function accept(row: Row) { try { await ElMessageBox.confirm(`确认接受 ${row.rfq_no} 的报价吗？`, "确认报价", { type: "warning" }); unwrap(await acceptRfq(row.id)); ElMessage.success("报价已接受"); await load(); } catch (error: any) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "接受报价失败"); } }
function openScore() { Object.assign(scoreForm, { supplier_id: suppliers.value[0]?.value || "", period: new Date().toISOString().slice(0, 7), delivery_score: 0, quality_score: 0, service_score: 0, evidence: { source: "manual_review" } }); scoreVisible.value = true; }
async function saveScore() { if (!scoreForm.supplier_id) return ElMessage.warning("请选择供应商"); try { unwrap(await createSupplierScore(scoreForm)); ElMessage.success("供应商评分已保存"); scoreVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "供应商评分保存失败"); } }
onMounted(() => Promise.all([load(), loadOptions(["suppliers"]) ]));
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>SRM / SUPPLIER COLLABORATION</small><h1>供应商协同工作台</h1><p>询报价、报价比价、承诺交期、交付差异与供应商质量评分共用一条可追溯链路。</p></div><el-space><el-button type="primary" @click="openCreate">新建询价</el-button><el-button type="success" plain @click="openScore">录入供应商评分</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header><el-alert title="报价接受前必须存在供应商报价；比价按已报价供应商的价格和承诺交期排序，评分按交付、质量、服务三项留存证据。" type="info" show-icon /><div class="toolbar"><el-input v-model="rfqFilters.rfqNo" placeholder="询价单号" clearable style="width: 160px" /><el-input v-model="rfqFilters.supplier" placeholder="供应商" clearable style="width: 160px" /><el-input v-model="rfqFilters.material" placeholder="物料" clearable style="width: 160px" /><el-select v-model="rfqFilters.status" placeholder="状态" clearable style="width: 140px"><el-option label="草稿" value="draft" /><el-option label="已报价" value="quoted" /><el-option label="已接受" value="accepted" /></el-select></div>
    <el-card shadow="never"><template #header><div class="card-header"><span>询价与供应商报价</span><el-button link type="primary" @click="loadCompare">刷新比价</el-button></div></template><el-table v-loading="loading" :data="rfqRows" stripe><el-table-column prop="rfq_no" label="询价单号" width="160" /><el-table-column label="供应商" min-width="160"><template #default="scope">{{ supplierLabel(scope.row.supplier_id) }}</template></el-table-column><el-table-column prop="material_id" label="物料" /><el-table-column prop="quantity" label="数量" /><el-table-column prop="quote_amount" label="报价" /><el-table-column prop="promised_date" label="承诺交期" /><el-table-column prop="status" label="状态" /><el-table-column label="操作" width="180"><template #default="scope"><el-button v-if="scope.row.status !== 'accepted'" link type="primary" @click="openQuote(scope.row)">录入报价</el-button><el-button v-if="scope.row.status === 'quoted'" link type="success" @click="accept(scope.row)">接受</el-button></template></el-table-column><template #empty><el-empty description="暂无供应商询价" /></template></el-table><ClientPagination v-model:page="rfqPage" v-model:page-size="rfqPageSize" :total="rfqTotal" @update:page-size="updateRfqPageSize" /></el-card>
    <el-card shadow="never"><template #header><div class="card-header"><span>报价比价</span><el-input v-model="compareMaterial" placeholder="按物料 ID 筛选" clearable style="width: 220px" @keyup.enter="loadCompare" /></div></template><el-table :data="comparePageRows" stripe><el-table-column prop="rank" label="排名" width="80" /><el-table-column label="供应商"><template #default="scope">{{ supplierLabel(scope.row.supplier_id) }}</template></el-table-column><el-table-column prop="material_id" label="物料" /><el-table-column prop="quote_amount" label="报价" /><el-table-column prop="promised_date" label="承诺交期" /><el-table-column prop="rfq_no" label="询价单号" /></el-table><ClientPagination v-model:page="comparePage" v-model:page-size="comparePageSize" :total="compareTotal" @update:page-size="updateComparePageSize" /></el-card>
    <el-card shadow="never"><template #header>供应商绩效评分</template><el-table :data="scoreRows" stripe><el-table-column label="供应商"><template #default="scope">{{ supplierLabel(scope.row.supplier_id) }}</template></el-table-column><el-table-column prop="period" label="期间" /><el-table-column prop="delivery_score" label="交付" /><el-table-column prop="quality_score" label="质量" /><el-table-column prop="service_score" label="服务" /><el-table-column prop="total_score" label="总分" /></el-table><ClientPagination v-model:page="scorePage" v-model:page-size="scorePageSize" :total="scoreTotal" @update:page-size="updateScorePageSize" /></el-card>
    <el-dialog v-model="visible" title="新建供应商询价" width="520px"><el-form label-width="90px"><el-form-item label="供应商" required><el-select v-model="form.supplier_id" filterable><el-option v-for="item in suppliers" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="物料 ID" required><el-input v-model="form.material_id" /></el-form-item><el-form-item label="数量" required><el-input-number v-model="form.quantity" :min="0.000001" /></el-form-item><el-form-item label="需求日期"><el-date-picker v-model="form.due_date" value-format="YYYY-MM-DD" /></el-form-item></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" @click="save">创建</el-button></template></el-dialog>
    <el-dialog v-model="quoteVisible" title="录入供应商报价" width="520px"><el-form label-width="90px"><el-form-item label="报价" required><el-input-number v-model="quoteForm.quote_amount" :min="0.01" :precision="2" /></el-form-item><el-form-item label="承诺交期"><el-date-picker v-model="quoteForm.promised_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="备注"><el-input v-model="quoteForm.supplier_note" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="quoteVisible = false">取消</el-button><el-button type="primary" @click="saveQuote">保存</el-button></template></el-dialog>
    <el-dialog v-model="scoreVisible" title="录入供应商评分" width="560px"><el-form label-width="90px"><el-form-item label="供应商" required><el-select v-model="scoreForm.supplier_id"><el-option v-for="item in suppliers" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="期间"><el-input v-model="scoreForm.period" /></el-form-item><el-form-item label="交付"><el-input-number v-model="scoreForm.delivery_score" :min="0" :max="100" /></el-form-item><el-form-item label="质量"><el-input-number v-model="scoreForm.quality_score" :min="0" :max="100" /></el-form-item><el-form-item label="服务"><el-input-number v-model="scoreForm.service_score" :min="0" :max="100" /></el-form-item></el-form><template #footer><el-button @click="scoreVisible = false">取消</el-button><el-button type="primary" @click="saveScore">保存评分</el-button></template></el-dialog>
  </section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.card-header{display:flex;justify-content:space-between;align-items:center}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:12px 0}.status-tag{border-width:1px}</style>
