<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { acceptRfq, createRfq, listRfqs, quoteRfq } from "../../api/phase2";
import { useMasterOptions } from "../../composables/useMasterOptions";
type Row = Record<string, any>;
const rows=ref<Row[]>([]); const loading=ref(false); const saving=ref(false); const visible=ref(false); const quoteVisible=ref(false); const selected=ref<Row|null>(null); const { suppliers, loadOptions }=useMasterOptions();
const form=reactive({supplier_id:"",material_id:"",quantity:1,due_date:""}); const quoteForm=reactive({quote_amount:0,promised_date:"",supplier_note:""});
function unwrap(r:any){if(r?.data?.code!==0)throw new Error(r?.data?.msg||"接口返回失败");return r.data.data}
async function load(){loading.value=true;try{rows.value=unwrap(await listRfqs())||[]}catch(e){ElMessage.error(e instanceof Error?e.message:"供应商协同加载失败")}finally{loading.value=false}}
function openCreate(){Object.assign(form,{supplier_id:"",material_id:"",quantity:1,due_date:""});visible.value=true}
async function save(){if(!form.supplier_id||!form.material_id||form.quantity<=0){ElMessage.warning("请选择供应商、物料并填写有效数量");return} saving.value=true;try{unwrap(await createRfq({...form}));ElMessage.success("询价已创建");visible.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:"询价创建失败")}finally{saving.value=false}}
function openQuote(row:Row){selected.value=row;Object.assign(quoteForm,{quote_amount:Number(row.quote_amount||0),promised_date:row.promised_date||"",supplier_note:row.supplier_note||""});quoteVisible.value=true}
async function saveQuote(){if(!selected.value||quoteForm.quote_amount<=0){ElMessage.warning("请填写有效报价");return}try{unwrap(await quoteRfq(selected.value.id,{...quoteForm}));ElMessage.success("供应商报价已保存");quoteVisible.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:"报价保存失败")}}
async function accept(row:Row){try{await ElMessageBox.confirm(`确认接受 ${row.rfq_no} 的报价吗？`,"确认报价",{type:"warning"});unwrap(await acceptRfq(row.id));ElMessage.success("报价已接受");await load()}catch(e:any){if(e!=="cancel"&&e!=="close")ElMessage.error(e instanceof Error?e.message:"接受报价失败")}}
onMounted(()=>Promise.all([load(),loadOptions(["suppliers"]) ]));
</script>
<template><section class="page-stack"><header class="page-heading"><div><small>SRM / SUPPLIER COLLABORATION</small><h1>供应商协同工作台</h1><p>询报价、承诺交期、交付差异与供应商质量评分共用一条可追溯链路。</p></div><el-space><el-button type="primary" @click="openCreate">新建询价</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header><el-alert title="报价接受前必须存在供应商报价；状态流转和重复提交由接口幂等保护。" type="info" show-icon/><el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="rfq_no" label="询价单号" width="160"/><el-table-column label="供应商" min-width="160"><template #default="scope">{{suppliers.find((item)=>item.value===scope.row.supplier_id)?.label||scope.row.supplier_id}}</template></el-table-column><el-table-column prop="material_id" label="物料"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="quote_amount" label="报价"/><el-table-column prop="promised_date" label="承诺交期"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="180"><template #default="scope"><el-button v-if="scope.row.status!=='accepted'" link type="primary" @click="openQuote(scope.row)">录入报价</el-button><el-button v-if="scope.row.status==='quoted'" link type="success" @click="accept(scope.row)">接受</el-button></template></el-table-column><template #empty><el-empty description="暂无供应商询价"/></template></el-table></el-card><el-dialog v-model="visible" title="新建供应商询价" width="520px"><el-form label-width="90px"><el-form-item label="供应商" required><el-select v-model="form.supplier_id" filterable><el-option v-for="item in suppliers" :key="item.value" v-bind="item"/></el-select></el-form-item><el-form-item label="物料 ID" required><el-input v-model="form.material_id"/></el-form-item><el-form-item label="数量" required><el-input-number v-model="form.quantity" :min="0.000001"/></el-form-item><el-form-item label="需求日期"><el-date-picker v-model="form.due_date" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建</el-button></template></el-dialog><el-dialog v-model="quoteVisible" title="录入供应商报价" width="520px"><el-form label-width="90px"><el-form-item label="报价" required><el-input-number v-model="quoteForm.quote_amount" :min="0.01" :precision="2"/></el-form-item><el-form-item label="承诺交期"><el-date-picker v-model="quoteForm.promised_date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="备注"><el-input v-model="quoteForm.supplier_note" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="quoteVisible=false">取消</el-button><el-button type="primary" @click="saveQuote">保存报价</el-button></template></el-dialog></section></template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}</style>
