<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { listEmployees, listPayroll, listPayrollDetails } from "../../api/hr";
import { createBenefit, createCandidate, createLifecycle, listBenefits, listCandidates, listLifecycle, listPerformance, savePerformance, updateCandidate } from "../../api/advanced";
import { useClientPagination } from "../../composables/useClientPagination";

type Row = Record<string, any>;
const employees = ref<Row[]>([]); const candidates = ref<Row[]>([]); const lifecycle = ref<Row[]>([]); const performance = ref<Row[]>([]); const benefits = ref<Row[]>([]); const payroll = ref<Row[]>([]); const payrollDetails = ref<Row[]>([]);
const loading = ref(false); const saving = ref(false); const activeTab = ref("candidates"); const dialog = ref("");
const { pagedRows: candidateRows, page: candidatePage, pageSize: candidatePageSize, total: candidateTotal, updatePageSize: updateCandidatePageSize } = useClientPagination(candidates);
const { pagedRows: lifecycleRows, page: lifecyclePage, pageSize: lifecyclePageSize, total: lifecycleTotal, updatePageSize: updateLifecyclePageSize } = useClientPagination(lifecycle);
const { pagedRows: performanceRows, page: performancePage, pageSize: performancePageSize, total: performanceTotal, updatePageSize: updatePerformancePageSize } = useClientPagination(performance);
const { pagedRows: benefitRows, page: benefitPage, pageSize: benefitPageSize, total: benefitTotal, updatePageSize: updateBenefitPageSize } = useClientPagination(benefits);
const { pagedRows: payrollRows, page: payrollPage, pageSize: payrollPageSize, total: payrollTotal, updatePageSize: updatePayrollPageSize } = useClientPagination(payroll);
const { pagedRows: payrollDetailRows, page: payrollDetailPage, pageSize: payrollDetailPageSize, total: payrollDetailTotal, updatePageSize: updatePayrollDetailPageSize } = useClientPagination(payrollDetails);
const candidateForm = reactive({ name: "", phone: "", position: "", source: "", note: "" }); const lifecycleForm = reactive({ employee_id: "", event_type: "onboarding", effective_date: "", to_status: "active", note: "" }); const performanceForm = reactive({ employee_id: "", period: new Date().toISOString().slice(0, 7), score: 0, rating: "pending", goals: [] as Row[], comments: "" }); const benefitForm = reactive({ employee_id: "", benefit_type: "social_insurance", amount: 0, effective_date: "", note: "" });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
function employeeLabel(id: string) { const row = employees.value.find((item) => item.id === id); return row ? `${row.employee_no} · ${row.name}` : id || "-"; }
async function load() { loading.value = true; try { [employees.value, candidates.value, lifecycle.value, performance.value, benefits.value, payroll.value] = await Promise.all([listEmployees().then(unwrap), listCandidates().then(unwrap), listLifecycle().then(unwrap), listPerformance().then(unwrap), listBenefits().then(unwrap), listPayroll().then(unwrap)]); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "人事运营加载失败"); } finally { loading.value = false; } }
function open(kind: string, row?: Row) { dialog.value = kind; if (kind === "candidate") Object.assign(candidateForm, { name: "", phone: "", position: "", source: "", note: "" }); if (kind === "lifecycle") Object.assign(lifecycleForm, { employee_id: employees.value[0]?.id || "", event_type: "onboarding", effective_date: "", to_status: "active", note: "" }); if (kind === "performance") Object.assign(performanceForm, { employee_id: row?.employee_id || employees.value[0]?.id || "", period: row?.period || new Date().toISOString().slice(0, 7), score: Number(row?.score || 0), rating: row?.rating || "pending", goals: row?.goals_json || [], comments: row?.comments || "" }); if (kind === "benefit") Object.assign(benefitForm, { employee_id: employees.value[0]?.id || "", benefit_type: "social_insurance", amount: 0, effective_date: "", note: "" }); }
async function saveAction(action: () => Promise<any>, message: string) { saving.value = true; try { unwrap(await action()); ElMessage.success(message); dialog.value = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } finally { saving.value = false; } }
async function saveCandidate() { if (!candidateForm.name || !candidateForm.position) return ElMessage.warning("请填写候选人姓名和应聘岗位"); await saveAction(() => createCandidate(candidateForm), "候选人已创建"); }
async function saveLifecycle() { if (!lifecycleForm.employee_id || !lifecycleForm.effective_date) return ElMessage.warning("请选择员工和生效日期"); await saveAction(() => createLifecycle(lifecycleForm), "人事异动已登记"); }
async function saveReview() { if (!performanceForm.employee_id || !performanceForm.period) return ElMessage.warning("请选择员工和考核期间"); await saveAction(() => savePerformance(performanceForm), "绩效已保存"); }
async function saveBenefit() { if (!benefitForm.employee_id || !benefitForm.effective_date) return ElMessage.warning("请选择员工和生效日期"); await saveAction(() => createBenefit(benefitForm), "福利记录已保存"); }
async function updateCandidateStatus(row: Row, status: string) { try { unwrap(await updateCandidate(row.id, { status, note: row.note || null })); ElMessage.success("候选人状态已更新"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "状态更新失败"); } }
async function showPayroll(row: Row) { try { payrollDetails.value = unwrap(await listPayrollDetails(row.id)) || []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "薪资明细加载失败"); } }
onMounted(load);
</script>

<template>
  <section class="page-stack"><header class="page-heading"><div><small>HR / PEOPLE OPERATIONS</small><h1>人事全生命周期中心</h1><p>覆盖招聘、入转调离、绩效、福利与薪资明细，员工状态变化保留可追溯记录。</p></div><el-button :loading="loading" @click="load">刷新</el-button></header>
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="招聘" name="candidates"><div class="toolbar"><el-button type="primary" @click="open('candidate')">新增候选人</el-button></div><el-table :data="candidateRows" stripe><el-table-column prop="candidate_no" label="候选人编号" /><el-table-column prop="name" label="姓名" /><el-table-column prop="phone" label="电话" /><el-table-column prop="position" label="岗位" /><el-table-column prop="source" label="来源" /><el-table-column prop="status" label="状态" /><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status === 'new'" link type="primary" @click="updateCandidateStatus(scope.row, 'interview')">进入面试</el-button><el-button v-if="scope.row.status === 'interview'" link type="success" @click="updateCandidateStatus(scope.row, 'hired')">录用</el-button><el-button v-if="['new','interview'].includes(scope.row.status)" link type="danger" @click="updateCandidateStatus(scope.row, 'rejected')">淘汰</el-button></template></el-table-column></el-table><ClientPagination v-model:page="candidatePage" v-model:page-size="candidatePageSize" :total="candidateTotal" @update:page-size="updateCandidatePageSize" /></el-tab-pane>
      <el-tab-pane label="入转调离" name="lifecycle"><div class="toolbar"><el-button type="primary" @click="open('lifecycle')">登记人事异动</el-button></div><el-table :data="lifecycleRows" stripe><el-table-column label="员工"><template #default="scope">{{ employeeLabel(scope.row.employee_id) }}</template></el-table-column><el-table-column prop="event_type" label="事件" /><el-table-column prop="effective_date" label="生效日期" /><el-table-column prop="from_status" label="原状态" /><el-table-column prop="to_status" label="新状态" /><el-table-column prop="note" label="备注" /></el-table><ClientPagination v-model:page="lifecyclePage" v-model:page-size="lifecyclePageSize" :total="lifecycleTotal" @update:page-size="updateLifecyclePageSize" /></el-tab-pane>
      <el-tab-pane label="绩效" name="performance"><div class="toolbar"><el-button type="primary" @click="open('performance')">新增/更新绩效</el-button></div><el-table :data="performanceRows" stripe><el-table-column label="员工"><template #default="scope">{{ employeeLabel(scope.row.employee_id) }}</template></el-table-column><el-table-column prop="period" label="期间" /><el-table-column prop="score" label="得分" /><el-table-column prop="rating" label="评级" /><el-table-column prop="status" label="状态" /><el-table-column label="操作"><template #default="scope"><el-button link type="primary" @click="open('performance', scope.row)">编辑</el-button></template></el-table-column></el-table><ClientPagination v-model:page="performancePage" v-model:page-size="performancePageSize" :total="performanceTotal" @update:page-size="updatePerformancePageSize" /></el-tab-pane>
      <el-tab-pane label="福利" name="benefits"><div class="toolbar"><el-button type="primary" @click="open('benefit')">新增福利记录</el-button></div><el-table :data="benefitRows" stripe><el-table-column label="员工"><template #default="scope">{{ employeeLabel(scope.row.employee_id) }}</template></el-table-column><el-table-column prop="benefit_type" label="福利类型" /><el-table-column prop="amount" label="金额" /><el-table-column prop="effective_date" label="生效日期" /><el-table-column prop="status" label="状态" /></el-table><ClientPagination v-model:page="benefitPage" v-model:page-size="benefitPageSize" :total="benefitTotal" @update:page-size="updateBenefitPageSize" /></el-tab-pane>
      <el-tab-pane label="薪资明细" name="payroll"><el-table :data="payrollRows" stripe><el-table-column prop="period" label="期间" /><el-table-column prop="total_amount" label="总额" /><el-table-column prop="status" label="状态" /><el-table-column label="操作"><template #default="scope"><el-button link type="primary" @click="showPayroll(scope.row)">查看明细</el-button></template></el-table-column></el-table><ClientPagination v-model:page="payrollPage" v-model:page-size="payrollPageSize" :total="payrollTotal" @update:page-size="updatePayrollPageSize" /><el-divider /><el-table :data="payrollDetailRows" stripe><el-table-column prop="employee_no" label="工号" /><el-table-column prop="employee_name" label="姓名" /><el-table-column prop="base_amount" label="应发" /><el-table-column prop="absent_days" label="缺勤" width="70" /><el-table-column prop="late_days" label="迟到" width="70" /><el-table-column prop="leave_days" label="请假" width="70" /><el-table-column prop="deduction" label="扣款" /><el-table-column prop="amount" label="实发" /></el-table><ClientPagination v-model:page="payrollDetailPage" v-model:page-size="payrollDetailPageSize" :total="payrollDetailTotal" @update:page-size="updatePayrollDetailPageSize" /></el-tab-pane>
    </el-tabs>
    <el-dialog :model-value="dialog === 'candidate'" title="新增候选人" width="520px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="姓名" required><el-input v-model="candidateForm.name" /></el-form-item><el-form-item label="电话"><el-input v-model="candidateForm.phone" /></el-form-item><el-form-item label="应聘岗位" required><el-input v-model="candidateForm.position" /></el-form-item><el-form-item label="来源"><el-input v-model="candidateForm.source" /></el-form-item><el-form-item label="备注"><el-input v-model="candidateForm.note" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveCandidate">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'lifecycle'" title="登记人事异动" width="520px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="员工" required><el-select v-model="lifecycleForm.employee_id"><el-option v-for="item in employees" :key="item.id" :label="`${item.employee_no} · ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="事件"><el-select v-model="lifecycleForm.event_type"><el-option label="入职" value="onboarding" /><el-option label="转正" value="regularization" /><el-option label="调岗" value="transfer" /><el-option label="离职" value="offboarding" /></el-select></el-form-item><el-form-item label="生效日期" required><el-date-picker v-model="lifecycleForm.effective_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="新状态"><el-select v-model="lifecycleForm.to_status"><el-option label="在职" value="active" /><el-option label="停用" value="inactive" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="lifecycleForm.note" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveLifecycle">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'performance'" title="保存绩效" width="560px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="员工" required><el-select v-model="performanceForm.employee_id"><el-option v-for="item in employees" :key="item.id" :label="`${item.employee_no} · ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="期间" required><el-input v-model="performanceForm.period" /></el-form-item><el-form-item label="得分"><el-input-number v-model="performanceForm.score" :min="0" :max="100" /></el-form-item><el-form-item label="评级"><el-select v-model="performanceForm.rating"><el-option label="待评" value="pending" /><el-option label="优秀" value="excellent" /><el-option label="合格" value="qualified" /><el-option label="不合格" value="poor" /></el-select></el-form-item><el-form-item label="评语"><el-input v-model="performanceForm.comments" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveReview">保存</el-button></template></el-dialog>
    <el-dialog :model-value="dialog === 'benefit'" title="新增福利" width="520px" @update:model-value="(value: boolean) => { if (!value) dialog = ''; }"><el-form label-width="90px"><el-form-item label="员工" required><el-select v-model="benefitForm.employee_id"><el-option v-for="item in employees" :key="item.id" :label="`${item.employee_no} · ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="福利类型"><el-input v-model="benefitForm.benefit_type" /></el-form-item><el-form-item label="金额"><el-input-number v-model="benefitForm.amount" :min="0" /></el-form-item><el-form-item label="生效日期" required><el-date-picker v-model="benefitForm.effective_date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="备注"><el-input v-model="benefitForm.note" /></el-form-item></el-form><template #footer><el-button @click="dialog = ''">取消</el-button><el-button type="primary" :loading="saving" @click="saveBenefit">保存</el-button></template></el-dialog>
  </section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.toolbar{display:flex;gap:10px;margin-bottom:14px}</style>
