<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { listEmployees, recordAttendance } from "../../api/hr";
import { createLeaveRequest, listAttendance, listLeaveRequests, transitionLeaveRequest } from "../../api/phase2";

type Row = Record<string, any>;
const rows = ref<Row[]>([]); const attendanceRows = ref<Row[]>([]); const employees = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const visible = ref(false); const attendanceVisible = ref(false);
const form = reactive({ employee_id: "", leave_type: "annual", start_date: "", end_date: "", reason: "" });
const attendanceForm = reactive({ employee_id: "", attendance_date: "", status: "present" });
const statusLabels: Record<string, string> = { draft: "草稿", submitted: "待审批", approved: "已批准", rejected: "已驳回", cancelled: "已取消" };
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
function employeeLabel(id: string) { return employees.value.find((item) => item.id === id)?.name || id || "-"; }
async function load() { loading.value = true; try { [rows.value, attendanceRows.value] = await Promise.all([listLeaveRequests().then(unwrap), listAttendance().then(unwrap)]); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "人事流程加载失败"); } finally { loading.value = false; } }
async function loadEmployees() { try { employees.value = unwrap(await listEmployees()) || []; if (!form.employee_id) form.employee_id = employees.value[0]?.id || ""; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "员工列表加载失败"); } }
function openCreate() { Object.assign(form, { employee_id: employees.value[0]?.id || "", leave_type: "annual", start_date: "", end_date: "", reason: "" }); visible.value = true; }
function openAttendance() { Object.assign(attendanceForm, { employee_id: employees.value[0]?.id || "", attendance_date: "", status: "present" }); attendanceVisible.value = true; }
async function save() { if (!form.employee_id || !form.start_date || !form.end_date) return ElMessage.warning("请选择员工和请假日期"); saving.value = true; try { unwrap(await createLeaveRequest({ ...form })); ElMessage.success("请假申请已保存"); visible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "请假申请保存失败"); } finally { saving.value = false; } }
async function saveAttendance() { if (!attendanceForm.employee_id || !attendanceForm.attendance_date) return ElMessage.warning("请选择员工和考勤日期"); saving.value = true; try { const response = await recordAttendance(attendanceForm.employee_id, { attendance_date: attendanceForm.attendance_date, status: attendanceForm.status }); unwrap(response); ElMessage.success("考勤已登记"); attendanceVisible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "考勤登记失败"); } finally { saving.value = false; } }
async function transition(row: Row, status: string) { try { await ElMessageBox.confirm(`确认将申请变更为“${statusLabels[status] || status}”吗？`, "操作确认", { type: "warning" }); unwrap(await transitionLeaveRequest(row.id, status)); ElMessage.success("状态已更新"); await load(); } catch (error: any) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "状态更新失败"); } }
onMounted(() => Promise.all([load(), loadEmployees()]));
</script>

<template>
  <section class="page-stack"><header class="page-heading"><div><small>HR / LEAVE</small><h1>考勤与请假中心</h1><p>维护考勤登记、请假申请、审批状态与员工人事流程记录。</p></div><el-space><el-button type="primary" @click="openCreate">新建请假申请</el-button><el-button @click="openAttendance">登记考勤</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header>
    <el-card shadow="never"><template #header>考勤记录</template><el-table :data="attendanceRows" stripe><el-table-column label="员工" min-width="140"><template #default="scope">{{ employeeLabel(scope.row.employee_id) }}</template></el-table-column><el-table-column prop="attendance_date" label="日期" /><el-table-column prop="status" label="状态" /></el-table></el-card>
    <el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column label="员工" min-width="140"><template #default="scope">{{ employeeLabel(scope.row.employee_id) }}</template></el-table-column><el-table-column prop="leave_type" label="类型" width="120" /><el-table-column prop="start_date" label="开始日期" /><el-table-column prop="end_date" label="结束日期" /><el-table-column prop="reason" label="原因" min-width="220" /><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.status === 'approved' ? 'success' : scope.row.status === 'rejected' ? 'danger' : 'warning'">{{ statusLabels[scope.row.status] || scope.row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="220"><template #default="scope"><el-button v-if="scope.row.status === 'draft'" link type="primary" @click="transition(scope.row, 'submitted')">提交审批</el-button><el-button v-if="scope.row.status === 'submitted'" link type="success" @click="transition(scope.row, 'approved')">批准</el-button><el-button v-if="scope.row.status === 'submitted'" link type="danger" @click="transition(scope.row, 'rejected')">驳回</el-button><el-button v-if="scope.row.status === 'draft'" link type="info" @click="transition(scope.row, 'cancelled')">取消</el-button></template></el-table-column><template #empty><el-empty description="暂无请假申请" /></template></el-table></el-card>
    <el-dialog v-model="visible" title="新建请假申请" width="560px"><el-form label-width="100px"><el-form-item label="员工" required><el-select v-model="form.employee_id" filterable style="width: 100%"><el-option v-for="item in employees" :key="item.id" :label="`${item.employee_no} - ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="请假类型" required><el-select v-model="form.leave_type" style="width: 100%"><el-option label="年假" value="annual" /><el-option label="病假" value="sick" /><el-option label="事假" value="personal" /><el-option label="调休" value="compensatory" /></el-select></el-form-item><el-form-item label="日期范围" required><el-date-picker v-model="form.start_date" type="date" value-format="YYYY-MM-DD" /><el-date-picker v-model="form.end_date" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="原因"><el-input v-model="form.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存草稿</el-button></template></el-dialog>
    <el-dialog v-model="attendanceVisible" title="登记考勤" width="480px"><el-form label-width="90px"><el-form-item label="员工" required><el-select v-model="attendanceForm.employee_id" style="width:100%"><el-option v-for="item in employees" :key="item.id" :label="`${item.employee_no} - ${item.name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="日期" required><el-date-picker v-model="attendanceForm.attendance_date" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="状态"><el-select v-model="attendanceForm.status"><el-option label="出勤" value="present" /><el-option label="缺勤" value="absent" /><el-option label="迟到" value="late" /><el-option label="请假" value="leave" /></el-select></el-form-item></el-form><template #footer><el-button @click="attendanceVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAttendance">登记</el-button></template></el-dialog>
  </section>
</template>

<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}</style>
