<script setup lang="ts">
import { onMounted, reactive, ref, watch } from "vue";
import { ElMessage } from "element-plus";
import { createBatch, listBatches } from "../../api/inventory-advanced";
import { useMasterOptions } from "../../composables/useMasterOptions";
const rows = ref<any[]>([]); const loading = ref(false); const saving = ref(false); const visible = ref(false); const form = reactive({ material_id: "", batch_no: "", production_date: "", expiry_date: "" });
const { materials, loadOptions } = useMasterOptions();
async function load() { loading.value = true; try { const response = await listBatches(form.material_id || undefined); if (response.data.code !== 0) throw new Error(response.data.msg); rows.value = response.data.data || []; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "批次加载失败"); } finally { loading.value = false; } }
function openCreate() { form.batch_no = ""; form.production_date = ""; form.expiry_date = ""; visible.value = true; }
async function save() { if (!form.material_id || !form.batch_no.trim()) { ElMessage.warning("请选择物料并填写批次号"); return; } saving.value = true; try { const response = await createBatch(form.material_id, { batch_no: form.batch_no.trim(), production_date: form.production_date || null, expiry_date: form.expiry_date || null }); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success("批次已创建"); visible.value = false; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "批次创建失败"); } finally { saving.value = false; } }
watch(() => form.material_id, load); onMounted(() => Promise.all([load(), loadOptions(["materials"])]));
</script>
<template><section class="page-stack"><el-page-header content="批次管理" /><el-space><el-select v-model="form.material_id" filterable clearable placeholder="全部物料" style="width: 250px"><el-option v-for="item in materials" :key="item.value" v-bind="item" /></el-select><el-button type="primary" @click="openCreate">新增批次</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="batch_no" label="批次号" min-width="200" /><el-table-column prop="material_id" label="物料" min-width="220" /><el-table-column prop="production_date" label="生产日期" width="140" /><el-table-column prop="expiry_date" label="失效日期" width="140" /><el-table-column prop="status" label="状态" width="110" /><template #empty><el-empty description="暂无批次" /></template></el-table><el-dialog v-model="visible" title="新增批次" width="500px"><el-form label-width="90px"><el-form-item label="物料" required><el-select v-model="form.material_id" filterable style="width: 100%"><el-option v-for="item in materials" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="批次号" required><el-input v-model="form.batch_no" /></el-form-item><el-form-item label="生产日期"><el-date-picker v-model="form.production_date" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="失效日期"><el-date-picker v-model="form.expiry_date" type="date" value-format="YYYY-MM-DD" /></el-form-item></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.page-stack { display: flex; flex-direction: column; gap: 16px; }</style>
