<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { createReservation, listReservations, listTraceEvents, releaseReservation } from "../../api/inventory-advanced";
import { useMasterOptions } from "../../composables/useMasterOptions";
type Row = Record<string, any>;
const tab = ref("reservations"); const loading = ref(false); const saving = ref(false); const reservations = ref<Row[]>([]); const trace = ref<Row[]>([]); const reservationStatus = ref(""); const traceFilters = reactive({ material_id: "", batch_id: "" });
const form = reactive({ source_type: "sales_order", source_id: "", material_id: "", warehouse_id: "", quantity: 1, note: "" });
const { materials, warehouses, loadOptions } = useMasterOptions();
function data(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口请求失败"); const value = response.data.data; return Array.isArray(value) ? value : Array.isArray(value?.items) ? value.items : []; }
function label(options: any[], id: any) { return options.find((item) => item.value === id)?.label || id || "-"; }
async function load() { loading.value = true; try { reservations.value = data(await listReservations(reservationStatus.value || undefined)); trace.value = data(await listTraceEvents({ material_id: traceFilters.material_id || undefined, batch_id: traceFilters.batch_id || undefined })); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "库存控制台加载失败"); } finally { loading.value = false; } }
async function reserve() { if (!form.source_id.trim() || !form.material_id || !form.warehouse_id || Number(form.quantity) <= 0) return ElMessage.warning("请填写来源单据、物料、仓库和有效数量"); saving.value = true; try { const response = await createReservation({ ...form, source_id: form.source_id.trim() }); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success("库存已预留"); form.source_id = ""; await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "库存预留失败"); } finally { saving.value = false; } }
async function release(row: Row) { await ElMessageBox.confirm("确认释放该库存预留？", "操作确认", { type: "warning" }); try { const response = await releaseReservation(row.id); if (response.data.code !== 0) throw new Error(response.data.msg); ElMessage.success("预留已释放"); await load(); } catch (error: any) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "释放失败"); } }
onMounted(async () => { try { await loadOptions(["materials", "warehouses"]); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "库存控制台基础数据加载失败"); } });
</script>
<template>
  <section class="page-stack"><el-page-header content="库存控制中心" /><el-alert title="预留会锁定可用库存；批次追溯展示已接入 FIFO 入库/出库事件。" type="info" show-icon /><el-alert v-if="!materials.length || !warehouses.length" title="暂无可用物料或仓库，当前不能创建库存预留。请先维护主数据。" type="warning" show-icon />
    <el-tabs v-model="tab" type="border-card"><el-tab-pane label="库存预留" name="reservations"><el-form inline class="control-form"><el-form-item label="状态"><el-select v-model="reservationStatus" clearable style="width: 120px" @change="load"><el-option label="预留中" value="reserved" /><el-option label="已释放" value="released" /></el-select></el-form-item><el-form-item label="来源类型"><el-select v-model="form.source_type" style="width: 150px"><el-option label="销售订单" value="sales_order" /><el-option label="生产工单" value="work_order" /><el-option label="采购申请" value="purchase_request" /></el-select></el-form-item><el-form-item label="来源单据"><el-input v-model="form.source_id" placeholder="单据 ID" /></el-form-item><el-form-item label="物料"><el-select v-model="form.material_id" filterable clearable style="width: 180px"><el-option v-for="item in materials" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="仓库"><el-select v-model="form.warehouse_id" filterable clearable style="width: 180px"><el-option v-for="item in warehouses" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="数量"><el-input-number v-model="form.quantity" :min="0.000001" :precision="6" /></el-form-item><el-button type="primary" :loading="saving" :disabled="!materials.length || !warehouses.length" @click="reserve">预留</el-button><el-button @click="load">刷新</el-button></el-form><el-table v-loading="loading" :data="reservations" stripe><el-table-column prop="source_type" label="来源" width="140" /><el-table-column prop="source_id" label="来源单据" min-width="180" /><el-table-column label="物料" min-width="160"><template #default="scope">{{ label(materials, scope.row.material_id) }}</template></el-table-column><el-table-column label="仓库" min-width="140"><template #default="scope">{{ label(warehouses, scope.row.warehouse_id) }}</template></el-table-column><el-table-column prop="quantity" label="预留总量" width="110" /><el-table-column prop="reserved_quantity" label="剩余预留" width="110" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="100"><template #default="scope"><el-button v-if="scope.row.status !== 'released'" link type="danger" @click="release(scope.row)">释放</el-button></template></el-table-column><template #empty><el-empty description="暂无库存预留记录" /></template></el-table></el-tab-pane>
      <el-tab-pane label="批次追溯" name="trace"><el-form inline class="control-form"><el-form-item label="物料"><el-select v-model="traceFilters.material_id" filterable clearable style="width: 200px"><el-option v-for="item in materials" :key="item.value" v-bind="item" /></el-select></el-form-item><el-form-item label="批次 ID"><el-input v-model="traceFilters.batch_id" clearable placeholder="可选批次 ID" /></el-form-item><el-button type="primary" @click="load">查询追溯</el-button><el-button @click="traceFilters.material_id = ''; traceFilters.batch_id = ''; load()">重置</el-button></el-form><el-table v-loading="loading" :data="trace" stripe><el-table-column prop="event_time" label="日期" width="120" /><el-table-column prop="direction" label="方向" width="90" /><el-table-column prop="source_type" label="来源类型" width="150" /><el-table-column prop="source_id" label="来源单据" min-width="180" /><el-table-column label="物料" min-width="160"><template #default="scope">{{ label(materials, scope.row.material_id) }}</template></el-table-column><el-table-column prop="batch_id" label="批次" min-width="150" /><el-table-column prop="quantity" label="数量" width="120" /><template #empty><el-empty description="暂无批次追溯事件" /></template></el-table></el-tab-pane></el-tabs>
  </section>
</template>
<style scoped>
.page-stack { display: flex; flex-direction: column; gap: 16px; }
.control-form { display: flex; flex-wrap: wrap; align-items: flex-end; column-gap: 12px; }
.control-form :deep(.el-form-item) { margin-right: 0; }
.control-form :deep(.el-button) { margin-bottom: 18px; }
</style>
