<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import { createIntercompany, createLowCode, createMetric, explainMetric, listAiAlerts, listIntercompany, listLowCode, listMetrics, listTaxInvoices, publishLowCode, resolveAiAlert, scanAiAlerts } from "../../api/phase2";

type Row = Record<string, any>;
const tab = ref("group"); const loading = ref(false); const intercompany = ref<Row[]>([]); const invoices = ref<Row[]>([]); const lowCode = ref<Row[]>([]); const metrics = ref<Row[]>([]); const alerts = ref<Row[]>([]); const metricDetail = ref<Row | null>(null);
const form = ref({ from_org_id: "", to_org_id: "", source_type: "", source_id: "", amount: 0, currency: "CNY" }); const lowForm = ref({ object_key: "", name: "", schema: '{"fields":[]}' }); const metricForm = ref({ metric_key: "", name: "", formula: "", target: null as number | null });
function unwrap(response: any) { if (response?.data?.code !== 0) throw new Error(response?.data?.msg || "接口返回失败"); return response.data.data; }
async function load() { loading.value = true; try { [intercompany.value, invoices.value, lowCode.value, metrics.value, alerts.value] = await Promise.all([listIntercompany().then(unwrap), listTaxInvoices().then(unwrap), listLowCode().then(unwrap), listMetrics().then(unwrap), listAiAlerts().then(unwrap)]); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "平台扩展加载失败"); } finally { loading.value = false; } }
async function saveGroup() { try { unwrap(await createIntercompany({ ...form.value })); ElMessage.success("内部交易已登记"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "内部交易保存失败"); } }
async function saveLow() { try { unwrap(await createLowCode({ object_key: lowForm.value.object_key, name: lowForm.value.name, schema: JSON.parse(lowForm.value.schema), workflow: {} })); ElMessage.success("低代码对象已保存"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "低代码对象保存失败"); } }
async function publish(row: Row) { try { unwrap(await publishLowCode(row.id)); ElMessage.success("低代码对象已发布"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "低代码发布失败"); } }
async function saveMetric() { try { unwrap(await createMetric(metricForm.value)); ElMessage.success("指标口径已保存"); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "指标保存失败"); } }
async function explain(row: Row) { try { metricDetail.value = unwrap(await explainMetric(row.metric_key)); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "指标解释失败"); } }
async function scan() { try { alerts.value = unwrap(await scanAiAlerts()) || []; ElMessage.success("异常扫描完成"); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "异常扫描失败"); } }
async function resolve(row: Row) { try { unwrap(await resolveAiAlert(row.id, "已由工作台处理")); await load(); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "异常关闭失败"); } }
onMounted(load);
</script>
<template>
  <section class="page-stack"><header class="page-heading"><div><small>GROUP / COMPLIANCE / PLATFORM</small><h1>集团与平台扩展中心</h1><p>统一管理内部交易、税务合规、低代码发布、指标语义和可解释异常助手。</p></div><el-space><el-button type="warning" @click="scan">扫描异常</el-button><el-button :loading="loading" @click="load">刷新</el-button></el-space></header>
    <el-tabs v-model="tab" type="border-card">
      <el-tab-pane label="集团内部交易" name="group"><el-form inline><el-form-item label="转出组织"><el-input v-model="form.from_org_id" /></el-form-item><el-form-item label="转入组织"><el-input v-model="form.to_org_id" /></el-form-item><el-form-item label="来源单据"><el-input v-model="form.source_id" /></el-form-item><el-form-item label="金额"><el-input-number v-model="form.amount" :min="0.01" /></el-form-item><el-button type="primary" @click="saveGroup">登记交易</el-button></el-form><el-table :data="intercompany" stripe><el-table-column prop="transaction_no" label="交易号" /><el-table-column prop="from_org_id" label="转出组织" /><el-table-column prop="to_org_id" label="转入组织" /><el-table-column prop="amount" label="金额" /><el-table-column prop="status" label="状态" /></el-table></el-tab-pane>
      <el-tab-pane label="税务与电子发票" name="compliance"><el-alert title="税码、发票状态和业务原单保持双向关系；电子发票服务接入前不允许伪造已开票状态。" type="info" show-icon /><el-descriptions :column="2" border><el-descriptions-item label="税码主数据">复用基础资料税率档案</el-descriptions-item><el-descriptions-item label="凭证关系">source_type + source_id</el-descriptions-item><el-descriptions-item label="红冲规则">仅已开具发票可进入红冲流程</el-descriptions-item><el-descriptions-item label="当前发票池">{{ invoices.length }} 条</el-descriptions-item></el-descriptions><el-table :data="invoices" stripe><el-table-column prop="invoice_no" label="发票号" /><el-table-column prop="invoice_type" label="类型" /><el-table-column prop="amount" label="金额" /><el-table-column prop="tax_amount" label="税额" /><el-table-column prop="status" label="状态" /></el-table></el-tab-pane>
      <el-tab-pane label="低代码发布" name="low-code"><el-form inline><el-form-item label="对象编码"><el-input v-model="lowForm.object_key" /></el-form-item><el-form-item label="对象名称"><el-input v-model="lowForm.name" /></el-form-item><el-form-item label="字段 JSON"><el-input v-model="lowForm.schema" /></el-form-item><el-button type="primary" @click="saveLow">保存对象</el-button></el-form><el-table :data="lowCode" stripe><el-table-column prop="object_key" label="对象" /><el-table-column prop="name" label="名称" /><el-table-column prop="status" label="状态" /><el-table-column prop="version" label="版本" /><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status !== 'published'" link type="primary" @click="publish(scope.row)">发布</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="指标与 AI 异常" name="metrics"><el-form inline><el-form-item label="指标编码"><el-input v-model="metricForm.metric_key" /></el-form-item><el-form-item label="名称"><el-input v-model="metricForm.name" /></el-form-item><el-form-item label="公式"><el-input v-model="metricForm.formula" /></el-form-item><el-button type="primary" @click="saveMetric">保存口径</el-button></el-form><el-divider content-position="left">指标口径</el-divider><el-table :data="metrics" stripe><el-table-column prop="metric_key" label="编码" /><el-table-column prop="name" label="名称" /><el-table-column prop="formula" label="公式" /><el-table-column label="操作"><template #default="scope"><el-button link type="primary" @click="explain(scope.row)">查看证据</el-button></template></el-table-column></el-table><el-divider content-position="left">异常助手</el-divider><el-table :data="alerts" stripe><el-table-column prop="title" label="异常" /><el-table-column prop="severity" label="严重度" /><el-table-column prop="recommended_action" label="建议动作" /><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status === 'open'" link type="success" @click="resolve(scope.row)">标记已处理</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs><el-drawer :model-value="Boolean(metricDetail)" title="指标证据" size="520px" @update:model-value="(value: boolean) => { if (!value) metricDetail = null; }"><el-descriptions v-if="metricDetail" :column="1" border><el-descriptions-item label="指标">{{ metricDetail.metric?.name }}</el-descriptions-item><el-descriptions-item label="公式">{{ metricDetail.metric?.formula }}</el-descriptions-item><el-descriptions-item label="质量">{{ metricDetail.quality }}</el-descriptions-item><el-descriptions-item label="证据">{{ metricDetail.evidence?.[0]?.message }}</el-descriptions-item></el-descriptions></el-drawer>
  </section>
</template>
<style scoped>.page-stack{display:flex;flex-direction:column;gap:16px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading small{color:var(--erp-muted-text);letter-spacing:.08em}.page-heading h1{margin:4px 0}.page-heading p{margin:0;color:var(--erp-muted-text)}.el-form{flex-wrap:wrap}</style>
